### ISSUE TITLE
Missing out variants for quantization ops.

### ISSUE THREAD

**Issue by rvijayc** [pytorch/executorch#1263]
Hi,

I am trying to run compiler passes on a edge graph that contains quantization ops (`quantized_decomposed.quantize_per_tensor`, ...), but I keep running into this error when running `ToOutVarPass`. May I know if I am doing something incorrect?

```
 <snipped>
  File "<snipped>/executorch/exir/passes/__init__.py", line 311, in ensures
    raise RuntimeError(f"Missing out variants: {self.missing_out_vars}")
RuntimeError: Missing out variants: {'quantized_decomposed::dequantize_per_tensor', 'quantized_decomposed::quantize_per_tensor'}
```

Related to this question is how I should add "out" variants for custom ops that I define myself. The [Torch.Library API Documentation](https://pytorch.org/docs/main/library.html) doesn't seem to address this.

Here is a minimal example to reproduce this issue:

```python
import IPython
import torch
import torch.nn as nn
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
        XNNPACKQuantizer, get_symmetric_quantization_config
        )

import executorch
from executorch.exir import EdgeProgramManager, to_edge

def quantize(m_pre, x_in):

    quantizer = XNNPACKQuantizer()
    quantizer.set_global(get_symmetric_quantization_config())
    m_annotated = prepare_pt2e(m_pre, quantizer)
    for x in x_in:
        m_annotated(x)
    return convert_pt2e(m_annotated, use_reference_representation=False)

# author a model.
model = nn.Sequential(
        nn.Linear(64, 64), 
        nn.ReLU(),
        nn.Linear(64, 32), 
        nn.ReLU()
        )
model = model.eval()

# generate a uniform distribution of data.
n_batches = 100
x_in = torch.distributions.uniform.Uniform(-1, 1).sample([n_batches, 64, 64])

# graph transformations to edge.
m_edge = to_edge(
            torch.export.export(
                quantize(
                    capture_pre_autograd_graph(model, (x_in[0,:],)),
                    x_in
                    ),
                (x_in[0,:],)
            )
        )

# run compiler passes on Edge graph.
from executorch.exir.passes import SpecPropPass, ToOutVarPass,MemoryPlanningPass
sp = SpecPropPass()
m_sp = sp(m_edge.exported_program().module()).graph_module
ov = ToOutVarPass()
m_ov = ov(m_sp).graph_module
```

**Comment by cccclai** [comment]
Orthogonal to the issue, since you run `XNNPACKQuantizer`, assuming you want to run the model with `XNNPACK` backend. Can we run `to_backend` after `to_edge`, following guidance here? https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html

Those quantized ops ideally will be lowed to XNNPACK backend

**Comment by cccclai** [comment]
Orthoganal to the issue, since you run `XNNPACKQuantizer`, assuming you want to run the model with `XNNPACK` backend. Can we run `to_backend` after `to_edge`, following guidance here? https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html

Those quantized ops ideally

**Comment by rvijayc** [comment]
> Orthogonal to the issue, since you run `XNNPACKQuantizer`, assuming you want to run the model with `XNNPACK` backend. Can we run `to_backend` after `to_edge`, following guidance here? https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html
> 
> Those quantized ops ideally will be lowed to XNNPACK backend

Thanks for the response. I am actually working on lowering to a custom built HW backend. I just used XNNPACK as an example to come with a minimal reproducible example. From your response, it seems like XNNPACK already has a solution to this problem? If so, I'd appreciate if you can point me to it. I'll review the XNNPACK code as well to see if I can find a solution.

**Comment by cccclai** [comment]
After quantizer, we'll see the quantized model representation like dequant -> op -> quant, which will be lowered to a backend, usually will be replaced by one actual quantized op, hence no longer interpreted by executor runtime later but only by the backend. Is it what you're looking for?

The missing out variants for `quantized_decomposed::dequantize_per_tensor` is something we'd need to fix though.

**Comment by rvijayc** [comment]
> After quantizer, we'll see the quantized model representation like dequant -> op -> quant, which will be lowered to a backend, usually will be replaced by one actual quantized op, hence no longer interpreted by executor runtime later but only by the backend. Is it what you're looking for?
> 
> The missing out variants for `quantized_decomposed::dequantize_per_tensor` is something we'd need to fix though.

Got it. That's exactly what I am doing as well. But, after the lowering, there will still be one quant and dequant Op that's left over at the edges of the graph. For example:

```
x -> q -> { dq -> op -> q } -> {  dq -> op -> q}  -> dq -> y
```

will become:

```
x -> q -> custom_op -> custom_op -> dq -> y
```

So, it seems like we'll still need to support the first and last `q` and `dq` ops.

**Comment by larryliu0820** [comment]
We have those ops defined in https://github.com/pytorch/executorch/blob/main/kernels/quantized/quantized.yaml#L13

It seems you need to build this library: [`aot_lib`](https://github.com/pytorch/executorch/blob/main/kernels/quantized/targets.bzl#L20) into a shared object and link that into your AOT compiler. See these steps as an example: https://github.com/pytorch/executorch/blob/main/examples/portable/custom_ops/test_custom_ops.sh#L55-L59

**Comment by rvijayc** [comment]
> We have those ops defined in https://github.com/pytorch/executorch/blob/main/kernels/quantized/quantized.yaml#L13
> 
> It seems you need to build this library: [`aot_lib`](https://github.com/pytorch/executorch/blob/main/kernels/quantized/targets.bzl#L20) into a shared object and link that into your AOT compiler. See these steps as an example: https://github.com/pytorch/executorch/blob/main/examples/portable/custom_ops/test_custom_ops.sh#L55-L59

Got it. Thanks for the pointer. I'll install it and try this again.

**Comment by rvijayc** [comment]
> We have those ops defined in https://github.com/pytorch/executorch/blob/main/kernels/quantized/quantized.yaml#L13
> 
> It seems you need to build this library: [`aot_lib`](https://github.com/pytorch/executorch/blob/main/kernels/quantized/targets.bzl#L20) into a shared object and link that into your AOT compiler. See these steps as an example: https://github.com/pytorch/executorch/blob/main/examples/portable/custom_ops/test_custom_ops.sh#L55-L59

I tried to run `test_custom_ops.sh` and ran into the same issue seen in https://github.com/pytorch/executorch/issues/1296. Is there something I am doing wrong here?  I am at tip git version (https://github.com/pytorch/executorch/commit/3a4bb06b3a3a36863ff9d7fca3cfee9d8f7b6613) and I did update all git submodules (so, I should have latest of `third-party/prelude` as well).

```
[workspace/git/executorch]$ examples/portable/custom_ops/test_custom_ops.sh cmake
Exporting custom_ops_1.pte
[INFO 2023-11-30 19:23:59,369 utils.py:36] Core ATen graph:
graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %mul3 : [num_users=1] = call_function[target=torch.ops.my_ops.mul3.default](args = (%arg0_1,), kwargs = {})
    return (mul3,)
[INFO 2023-11-30 19:23:59,400 utils.py:51] Exported graph:
graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %my_ops_mul3_default : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.my_ops.mul3.default](args = (%arg0_1,), kwargs = {})
    return (my_ops_mul3_default,)
/.../miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/_pytree.py:590: UserWarning: pytree_to_str is deprecated. Please use treespec_dumps
  warnings.warn("pytree_to_str is deprecated. Please use treespec_dumps")
[INFO 2023-11-30 19:23:59,416 utils.py:87] Saved exported program to custom_ops_1.pte
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- executorch: Generating source lists
-- executorch: Generating source file list /local/mnt/workspace/git/executorch/cmake-out/executorch_srcs.cmake
Error while generating /local/mnt/workspace/git/executorch/cmake-out/executorch_srcs.cmake. Exit code: 1
Output:

Error:
Traceback (most recent call last):
  File "/local/mnt/workspace/git/executorch/build/extract_sources.py", line 79, in run
    cp: subprocess.CompletedProcess = subprocess.run(
  File "/.../miniconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['buck2', 'cquery', "inputs(deps('//examples/portable/executor_runner:executor_runner'))"]' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local/mnt/workspace/git/executorch/build/extract_sources.py", line 235, in <module>
    main()
  File "/local/mnt/workspace/git/executorch/build/extract_sources.py", line 220, in main
    target_to_srcs[name] = sorted(target.get_sources(graph, runner))
  File "/local/mnt/workspace/git/executorch/build/extract_sources.py", line 133, in get_sources
    sources: set[str] = set(runner.run(["cquery", query]))
  File "/local/mnt/workspace/git/executorch/build/extract_sources.py", line 84, in run
    raise RuntimeError(ex.stderr.decode("utf-8")) from ex
RuntimeError: [2023-11-30T19:24:00.180-08:00] Build ID: f804d54c-2239-4a8e-919b-b1f8eb234c90
[2023-11-30T19:24:00.180-08:00] File changed: root//cmake-out/CMakeCache.txt.tmpe7a7a
[2023-11-30T19:24:00.180-08:00] File changed: root//cmake-out/CMakeCache.txt
[2023-11-30T19:24:00.180-08:00] File changed: root//cmake-out/CMakeFiles/cmake.check_cache
[2023-11-30T19:24:00.180-08:00] 88 additional file change events
Command failed:
From load at implicit location

Caused by:
    0: From load at third-party/prelude/prelude.bzl:8
    1: Error parsing: `prelude//native.bzl`
    2: error: list of 1 element expression is not allowed in type expression
          --> third-party/prelude/native.bzl:166:42
           |
       166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
           |                                          ^^^^^
           |

```

**Comment by larryliu0820** [comment]
I didn't mean to run test_custom_ops.sh directly, I meant you need to build the buck target I gave and link the shared object into the python environment, similar to what the script was doing.

**Comment by larryliu0820** [comment]
More concretely, what you really should do is write a script with the following command:

```bash
  SO_LIB=$($BUCK2 build //kernels/quantized:aot_lib --show-output | grep "buck-out" | cut -d" " -f2)

  ${PYTHON_EXECUTABLE} -m "<your_python_script>" --so_library="$SO_LIB"
```

In `your_python_script` you should have these lines:

```python
        if args.so_library:
            torch.ops.load_library(args.so_library)
```

as shown in https://github.com/pytorch/executorch/blob/main/examples/portable/custom_ops/custom_ops_2.py#L54-L56

**Comment by larryliu0820** [comment]
As for your buck2 error, I still believe there's something wrong with your buck2 installation or the state of ExecuTorch repo. Can you try reinstall everything and see if it works.

**Comment by mergennachin** [comment]
@claude what's the newest API to do PTQ?

**Comment by mergennachin** [comment]
@claude 

Convert to the latest API and usage

```
import IPython
import torch
import torch.nn as nn
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
        XNNPACKQuantizer, get_symmetric_quantization_config
        )

import executorch
from executorch.exir import EdgeProgramManager, to_edge

def quantize(m_pre, x_in):

    quantizer = XNNPACKQuantizer()
    quantizer.set_global(get_symmetric_quantization_config())
    m_annotated = prepare_pt2e(m_pre, quantizer)
    for x in x_in:
        m_annotated(x)
    return convert_pt2e(m_annotated, use_reference_representation=False)

# author a model.
model = nn.Sequential(
        nn.Linear(64, 64), 
        nn.ReLU(),
        nn.Linear(64, 32), 
        nn.ReLU()
        )
model = model.eval()

# generate a uniform distribution of data.
n_batches = 100
x_in = torch.distributions.uniform.Uniform(-1, 1).sample([n_batches, 64, 64])

# graph transformations to edge.
m_edge = to_edge(
            torch.export.export(
                quantize(
                    capture_pre_autograd_graph(model, (x_in[0,:],)),
                    x_in
                    ),
                (x_in[0,:],)
            )
        )

# run compiler passes on Edge graph.
from executorch.exir.passes import SpecPropPass, ToOutVarPass,MemoryPlanningPass
sp = SpecPropPass()
m_sp = sp(m_edge.exported_program().module()).graph_module
ov = ToOutVarPass()
m_ov = ov(m_sp).graph_module
```

**Comment by mergennachin** [comment]
The above code is working on colab notebook
