### ISSUE TITLE
export llama runtime error: Missing out variants: {'aten::_scaled_dot_product_flash_attention_for_cpu'}

### ISSUE THREAD

**Issue by huangzhiyuan** [pytorch/executorch#1577]
I met an runtime error when I attempt to export llama2 model in executorch as  instructions in https://github.com/pytorch/executorch/tree/5318baacd3500b56611eb6beb84cb19b2bae7f78/examples/models/llama2#instructions.

```
$ python3 -m examples.models.llama2.export_llama
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/test/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/workspace/mlc-llm/executorch/examples/models/llama2/export_llama.py", line 64, in <module>
    main()  # pragma: no cover
  File "/home/test/workspace/mlc-llm/executorch/examples/models/llama2/export_llama.py", line 56, in main
    export_program = edge_manager.to_executorch(
  File "/home/test/workspace/mlc-llm/executorch/exir/program/_program.py", line 1026, in to_executorch
    new_gm_res = p(new_gm)
  File "/home/test/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/infra/pass_base.py", line 40, in __call__
    res = self.call(graph_module)
  File "/home/test/workspace/mlc-llm/executorch/exir/passes/__init__.py", line 418, in call
    raise RuntimeError(f"Missing out variants: {missing_out_vars}")
RuntimeError: Missing out variants: {'aten::_scaled_dot_product_flash_attention_for_cpu'}
```

could someone please help with this error? thanks~

**Comment by guangy10** [comment]
This op is not in Core ATen opset. It should be decomposed and shouldn't show in the exported artifact. I think #117097 is fixing it. @larryliu0820 to confirm.
