### ISSUE TITLE
Quantization Error in official Llama2-7b pth model. 

### ISSUE THREAD

**Issue by kyungsoo3lee** [pytorch/executorch#1748]
I switched the official llama2-7b pth model. I success export pte model. 
and I wanna quantize(INT8) llama2-7b pth model.  but error is occurred. 

**1. Export & Quantize llama2-7b pth model**
```
python3 -m examples.models.llama2.export_llama --fairseq2 -Q --checkpoint ./examples/models/llama2/params/consolidated.00.pth --params ./examples/models/llama2/params/params.json
```

**2. Error is occurred.**
```
error:
  /tmp/tmpev7356gm/data.json:1: 122997: error: invalid number: "8388990224", constant does not fit [0; 4294967295]

Traceback (most recent call last):
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/platformsw/work/executorch-main/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File "/home/platformsw/work/executorch-main/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File "/home/platformsw/work/executorch-main/executorch/examples/models/llama2/export_llama_lib.py", line 204, in export_llama
    export_program = edge_manager.to_executorch(
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1048, in to_executorch
    return ExecutorchProgramManager(
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1102, in __init__
    self._buffer: bytes = _serialize_pte_binary(
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/_serialize/_program.py", line 554, in serialize_pte_binary
    result: _FlatbufferResult = _program_json_to_flatbuffer(
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/_serialize/_flatbuffer.py", line 281, in _program_json_to_flatbuffer
    _flatc_compile(temp_dir, schema_info.root_path, json_path)
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/_serialize/_flatbuffer.py", line 205, in _flatc_compile
    _run_flatc(
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/_serialize/_flatbuffer.py", line 191, in _run_flatc
    subprocess.run([flatc_path] + list(args), check=True)
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['flatc', '--binary', '-o', '/tmp/tmpev7356gm', '/tmp/tmpev7356gm/program.fbs', '/tmp/tmpev7356gm/data.json']' returned non-zero exit status 1.
```

**Comment by guangy10** [comment]
> error: invalid number: "8388990224", constant does not fit [0; 4294967295]

It exceeds the 4GB limit that our flatbuffer program schema could support. If you'd like to experiment it a bit, maybe you can temporarily modify the [program.fbs](https://github.com/pytorch/executorch/blob/f80c05c22aa825fdd76ceb5980149a662408f5b4/schema/program.fbs#L31) to unblock. 

@larryliu0820, @shoumikhin could comment more.

**Comment by kyungsoo3lee** [comment]
Hi @guangy10. Thank u response. 

**How to modify the program.fbs to unblock?**

**Comment by lucylq** [comment]
Try replacing `memory_offset:uint;` with `memory_offset:uint64;` in [program.fbs](https://github.com/pytorch/executorch/blob/schema/program.fbs#L31).

**Comment by JacobSzwejbka** [comment]
@dbort has a PR https://github.com/pytorch/executorch/pull/1792?fbclid=IwAR1NUAQwRpJG-bCneiBfqxLKqjl5NxBEPOHQtecH9K-UERi0oCs5ytbDZrQ that addresses this

**Comment by kyungsoo3lee** [comment]
I try to replace memory_offset program.fbs. 
but error is occurred yet. My PR is #1885.

**Comment by lucylq** [comment]
Confirming that you ran `pip install .` in the executorch directory before exporting again? Hmn, that PR takes me to "Fix TestEdgeYaml test" by @vmpuri

**Comment by kyungsoo3lee** [comment]
Thank u @lucylq 
Quantization was success!! :)
