### ISSUE TITLE
AttributeError: 'InputSpec' object has no attribute 'persistent'

### ISSUE THREAD

**Issue by kyungsoo3lee** [pytorch/executorch#1854]
Hi. 

1. My code is pr #1843.
```
HEAD is now at 05d2c935 Import _trace directly (#1843)
```

2. Attribute Error is occurred when I export llama2 model. 
```
python3 -m examples.models.llama2.export_llama --checkpoint ./examples/models/llama2/params/demo_rand_params.pth --params ./examples/models/llama2/params/demo_config.json
```
```
Traceback (most recent call last):
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/platformsw/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/models/llama2/export_llama_lib.py", line 158, in export_llama
    return _export_llama(modelname, args)
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/models/llama2/export_llama_lib.py", line 238, in _export_llama
    edge_manager = export_to_edge(
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/portable/utils.py", line 69, in export_to_edge
    return _core_aten_to_edge(core_aten_ep, edge_constant_methods, edge_compile_config)
  File "/home/platformsw/work/executorch-main-0206/executorch/examples/portable/utils.py", line 52, in _core_aten_to_edge
    edge_manager: EdgeProgramManager = to_edge(
  File "/home/platformsw/work/executorch-main/executorch/exir/program/_program.py", line 852, in to_edge
    graph_signature=_get_updated_graph_signature(
  File "/home/platformsw/work/executorch-main/executorch/exir/program/_program.py", line 85, in _get_updated_graph_signature
    persistent=old_input_spec.persistent,
AttributeError: 'InputSpec' object has no attribute 'persistent'
```

**Comment by anyj0527** [comment]
You may check https://github.com/pytorch/executorch/pull/1845. It fixed the issue in my local

**Comment by cccclai** [comment]
The fixes was landed (https://github.com/pytorch/executorch/pull/1855). Can you check again? Notice that we'll need to reinstall torch because of version bump
