### ISSUE TITLE
TypeError: 'staticmethod' object is not callable AND XnnpackPartitioner() flatc issue

### ISSUE THREAD

**Issue by adonnini** [pytorch/executorch#2025]
@mcr229 @kimishpatel asked me to create this issue and bring it to your attention.

I added strict=False to
export(pre_autograd_aten_dialect, (enc_input, dec_input, dec_source_mask, dec_target_mask))
When I ran the code, it failed at this line
lowered_module = edge_program.to_backend(XnnpackPartitioner())
Telling me it could not find flatc even though it is installed and available.

I am sorry I did not think to copy the traceback log.

Then, I had the bright idea (not really) to update executorch installation to the latest nightly build (20240209).
Now, execution fails with a brand new error. Please see traceback log below.
I searched for information on this error. I did not come up with anything I found useful, not to say that there wasn't relevant information. I just could not decipher whether it was applicable to my case
TRACEBACK LOG

Traceback (most recent call last):
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/train-minimum.py", line 21, in <module>
    from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/backends/xnnpack/__init__.py", line 8, in <module>
    from .partition.xnnpack_partitioner import (
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 82, in <module>
    class XnnpackOperatorSupport(OperatorSupportBase):
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 236, in XnnpackOperatorSupport
    @_constraint(exir_ops.edge.aten.mean.dim)
TypeError: 'staticmethod' object is not callable

**Comment by mcr229** [comment]
Hi adonnini, does this error also occur when you try running through any of the examples?

For example
```
python -m examples.xnnpack.aot_compiler -m="mv2" -d
```

**Comment by adonnini** [comment]
I never ran any of the examples. They are not meaningful for me. Even if I tried running them and they worked, it doesn't change the fact that execution fails when I run the code with my model.The outcome of running the examples should not change whether i run them or anyone else does.Did you try to run the examples?On Feb 22, 2024 21:02, Max Ren ***@***.***> wrote:
Hi adonnini, does this error also occur when you try running through any of the examples?
For example
python -m examples.xnnpack.aot_compiler -m="mv2" -d

**Comment by adonnini** [comment]
@mcr229 I never ran any of the examples. They are not meaningful for me. Even if I tried running them and they worked, it doesn't change the fact that execution fails when I run the code with my model.
The outcome of running the examples should not change whether i run them or anyone else does.
Did you try to run the examples?

**Comment by mcr229** [comment]
Hi @adonnini, the error you're encountering looks strange to me and seemed like it wasn't model specific, so I was wondering if you would encounter the same error if you ran the export of one of the example models. That's why I was asking if running any of the examples would cause the same error for you. I just wanted to see if this was a build specific issue or a model specific issue.

**Comment by adonnini** [comment]
@mcr229 I understand. It migh be helpful if I gave you the sequence of events that led to the error:
1) When trying to lower my model onto an Android device I was running  into 
```torch._dynamo.exc.Unsupported: call_function args:``` error
2) To work around the error it was suggested that is set ```strict``` to ```False```
3) Doing this seemed to solve the problem but caused a ```flatc``` missong/not found problem when running this line
```lowered_module = edge_program.to_backend(XnnpackPartitioner())```
4) To try and resolve this error, I updated executorch to the 20240209 nightly build
5) After the update, running my code failed with 
```TypeError: 'staticmethod' object is not callable```
I hope this helps.

**Comment by adonnini** [comment]
@mcr229 sorry about this. I tried to run the examples module as you instructed. Execution keeps failing with 
```No module named '/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/examples/xnnpack/aot_compiler')```
error even though ```aot_compiler.py``` is in the folder. Execution fails regardless of whether I use ```aot_compiler.py``` or ```aot_compiler```.
I must be doing something simple wrong. Sorry

**Comment by adonnini** [comment]
@mcr229  I ran

```python3 -m aot_compiler -m="mv2" -d```

Execution failed producing the following traceback log

```
Traceback (most recent call last):
  File "/home/adonnini1/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/adonnini1/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/examples/xnnpack/aot_compiler.py", line 14, in <module>
    from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/executorch/backends/xnnpack/__init__.py", line 8, in <module>
    from .partition.xnnpack_partitioner import (
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 82, in <module>
    class XnnpackOperatorSupport(OperatorSupportBase):
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 236, in XnnpackOperatorSupport
    @_constraint(exir_ops.edge.aten.mean.dim)
TypeError: 'staticmethod' object is not callable
```

**Comment by mcr229** [comment]
hi adonnini, it looks like the python version you're using is python 3.9. I believe we currently require 3.10+. I moved my python version to 3.9 as well and was able to replicate the error. Try creating a new conda env and installing python=3.10

**Comment by adonnini** [comment]
@mcr229 are you saying that that using python 3.9 is the cause of the error?

**Comment by mcr229** [comment]
yes I believe so

**Comment by dbort** [comment]
Sorry about the problems @adonnini. A few things:
- `bash: /tmp/buck2: Text file busy` typically means that a process is currently executing `buck2`. You could try killing all buck2 processes. Or you could `rm /tmp/buck2` first.
- PyTorch core currently supports python 3.10 but I don't believe that it supports 3.11 yet
- `error: invalid command 'bdist_wheel'` - Based on https://stackoverflow.com/a/44862371 you may need to `pip install wheel` in your venv. If that fixes it then we should update setup.py or install_requirements.sh to add that as a dep

**Comment by adonnini** [comment]
@mcr229 Thanks. I really appreciate your help.
Iran the commands listed in your last comment above.
Unfortunately, the result of
```./install_requirements.sh```

was the same
```
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/.executorch/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running dist_info
      copying from schema/scalar_type.fbs to exir/_serialize/scalar_type.fbs
      copying from schema/program.fbs to exir/_serialize/program.fbs
      copying from sdk/bundled_program/schema/bundled_program_schema.fbs to sdk/bundled_program/serialize/bundled_program_schema.fbs
      copying from sdk/bundled_program/schema/scalar_type.fbs to sdk/bundled_program/serialize/scalar_type.fbs
      creating /tmp/pip-modern-metadata-52tm45wt/executorch.egg-info
      writing /tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-52tm45wt/executorch.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-52tm45wt/executorch-0.1.0.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Version of /home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/third-party/flatbuffers is 23.5.26
A compatible version of flatc is on the PATH and ready to use.
```

**Comment by adonnini** [comment]
@dbort , Thanks. I followed your suggestions after running the commands in @mcr229 latest message. Please see below.
I did instal the latest version of ```wheel```.
As you will see when I ran 
```/tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output```
the build failed. Did I do something wrong?

```
(executorch_with_3.1) (.executorch) adonnini1@actlnxlptp6:~/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch$ rm /tmp/buck2
(executorch_with_3.1) (.executorch) adonnini1@actlnxlptp6:~/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch$ zstd -cdq /home/adonnini1/Downloads/buck2-x86_64-unknown-linux-musl.zst  > /tmp/buck2 && chmod +x /tmp/buck2
(executorch_with_3.1) (.executorch) adonnini1@actlnxlptp6:~/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch$ /tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output
From `load` at implicit location

Caused by:
    0: From `load` at third-party/prelude/prelude.bzl:8:6-29
    1: From `load` at third-party/prelude/native.bzl:15:6-45
    2: From `load` at third-party/prelude/apple/apple_macro_layer.bzl:8:6-32
    3: Error evaluating module: `prelude//apple/apple_bundle_config.bzl`
    4: error: Variable `typing` not found
         --> third-party/prelude/apple/apple_bundle_config.bzl:14:40
          |
       14 | def apple_bundle_config() -> dict[str, typing.Any]:
          |                                        ^^^^^^
          |
       
Build ID: 0de68684-c15d-482c-a9e8-82f4017c5d82
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
```

**Comment by mcr229** [comment]
cc @shoumikhin as it looks like this seems to be an issue with some apple stuff

**Comment by adonnini** [comment]
@lucylq Thanks. I will do as you say. 

@mcr229 Does fixing the buck2 issue solve my main problem, the failure of
```./install_requirements.sh```
even after following your isntructions (using python 3.10)
and the fact that lowering a model using ```(Xnnpack``` does not seem to be working?

Thanks

**Comment by mcr229** [comment]
Hi @adonnini are you still encountering the error: `TypeError: 'staticmethod' object is not callable` after updating to python 3.10? Again apologies for the difficulty with this set up.  I am hopeful that updating buck and using python3.10 will move us closer.

**Comment by adonnini** [comment]
@mcr229 , As I indicated in comments above, after following your instructions for use f python3.10:

1) ```./install_requirements.sh``` still faiuls (please see comments above for traceback log)
2) If I try to run my training module which includes the executorch code. It fails with this traceback:
```
Traceback (most recent call last):
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/train-minimum.py", line 12, in <module>
    import dataloader
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/dataloader.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```
What do you think I should do next?

**Comment by adonnini** [comment]
@lucylq I did as you suggested now all tasks related to buck2 work. Thanks!

**Comment by adonnini** [comment]
@mcr229 now that the buck2 related issue is resolved the only "infrastructure" related issue left is the one related to the failure of 
```./install_requirements.sh```
By the way,  I just ran these
```
conda create -yn executorch_with_3.1 python=3.10.0
conda activate executorch_with_3.1
./install_requirements.sh
```
Theresult was the same failure:
```
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running dist_info
      copying from schema/scalar_type.fbs to exir/_serialize/scalar_type.fbs
      copying from schema/program.fbs to exir/_serialize/program.fbs
      copying from sdk/bundled_program/schema/bundled_program_schema.fbs to sdk/bundled_program/serialize/bundled_program_schema.fbs
      copying from sdk/bundled_program/schema/scalar_type.fbs to sdk/bundled_program/serialize/scalar_type.fbs
      creating /tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info
      writing /tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-qtca28ux/UNKNOWN.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-qtca28ux/UNKNOWN.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Version of /home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/third-party/flatbuffers is 23.5.26
A compatible version of flatc is on the PATH and ready to use.
(executorch_with_3.1) (.executorch) adonnini1@actlnxlptp6:~/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch$ 
```

**Comment by adonnini** [comment]
@mcr229 , thanks. Actually, it looks like bdist_wheel does no have to be installed (pip does not recognize any such package). However, I did nee do run ```python setup.py bdist_wheel ```.
After doing that execution of  ```./install_requirements.sh``` completed apparently successfully with the message reported below. What do you think?
```
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=2001 sha256=5b2ff4dcc4f9bba9d26a1e28ed81447985bae7c6b17d4ef863ff810ee46e2027
  Stored in directory: /tmp/pip-ephem-wheel-cache-_kyb4365/wheels/6b/3e/55/9dd020d45f10b80c86dcf99ac07c1dbf2f510e38ab651ae59c
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
Version of /home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/executorch/third-party/flatbuffers is 23.5.26
A compatible version of flatc is on the PATH and ready to use.
```

**Comment by adonnini** [comment]
@mcr229 Although ```./install_requirements.sh``` seemed to complete successfully, when I ran training of my model (including the executorch code), the result was the same:
```
Traceback (most recent call last):
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/train-minimum.py", line 12, in <module>
    import dataloader
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/trajectory-prediction-transformers-master/dataloader.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by daniil-lyakhov** [comment]
Unfortunately, I've encountered the same issue:

```
from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner

/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:106: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_byte.out")
/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:153: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_byte.dtype_out")
/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:228: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_4bit.out")
/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:281: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_4bit.dtype_out")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/backends/xnnpack/__init__.py", line 8, in <module>
    from .partition.xnnpack_partitioner import (
  File "/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 88, in <module>
    class XnnpackOperatorSupport(OperatorSupportBase):
  File "/home/dlyakhov/env/executorch/lib/python3.9/site-packages/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 259, in XnnpackOperatorSupport
    @_constraint(exir_ops.edge.aten.mean.dim)
TypeError: 'staticmethod' object is not callable
```

```
pip freeze | grep torch

efficientnet_pytorch==0.7.1
executorch==0.3.0
torch==2.4.0
torchaudio==2.4.0
torchmetrics==1.0.1
torchvision==0.19.0
```

**Comment by mcr229** [comment]
Hi @daniil-lyakhov     
the:
```
@_constraint(exir_ops.edge.aten.mean.dim)
```
is no longer a part of the code path. I believe in the newer v0.5.0 release this shouldn't exist anymore. Seems like the general resolution for this was to use python 3.10. Closing for now, feel free to re-open if the issue persists.
