### ISSUE TITLE
Unable to run the iOS demo app 

### ISSUE THREAD

**Issue by byjlw** [pytorch/executorch#2203]
https://pytorch.org/executorch/stable/demo-apps-ios.html

Was able to resolve a number of issues up until this point but now I'm blocked. It appears there has been so change in how CMAKE works since this was put together. 
Running this command gives me a set of errors

`./build/build_apple_frameworks.sh --Release --coreml --mps --xnnpack
`
```
Building libraries
Building for iphoneos with flag OS
CMake Warning (dev) at third-party/pytorch/cmake/iOS.cmake:44 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  .executorch/lib/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:44 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third-party/pytorch/cmake/iOS.cmake:130 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  .executorch/lib/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:44 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk
CMake Warning (dev) at third-party/pytorch/cmake/iOS.cmake:44 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  cmake-out/iphoneos/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:44 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third-party/pytorch/cmake/iOS.cmake:130 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  cmake-out/iphoneos/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:44 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
CMake Error at /Users/byjlw/Documents/source/executorch/third-party/pytorch/cmake/iOS.cmake:44 (exec_program):
  The exec_program command should not be called; see CMP0153.  Use
  execute_process() instead.
Call Stack (most recent call first):
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/CMakeScratch/TryCompile-KmGsZL/CMakeLists.txt:4 (project)


CMake Error at /Users/byjlw/Documents/source/executorch/third-party/pytorch/cmake/iOS.cmake:130 (exec_program):
  The exec_program command should not be called; see CMP0153.  Use
  execute_process() instead.
Call Stack (most recent call first):
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/CMakeScratch/TryCompile-KmGsZL/CMakeLists.txt:4 (project)


CMake Error at /Users/byjlw/Documents/source/executorch/third-party/pytorch/cmake/iOS.cmake:150 (message):
  No iOS SDK's found in default search path .  Manually set
  CMAKE_IOS_SDK_ROOT or install the iOS SDK.
Call Stack (most recent call first):
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/3.28.3/CMakeSystem.cmake:6 (include)
  /Users/byjlw/Documents/source/executorch/cmake-out/iphoneos/CMakeFiles/CMakeScratch/TryCompile-KmGsZL/CMakeLists.txt:4 (project)


CMake Error at .executorch/lib/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  .executorch/lib/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:44 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by cccclai** [comment]
@shoumikhin any clue on this?

**Comment by shoumikhin** [comment]
Hi Jesse,

Please check out the steps in [test_ios.sh](https://github.com/pytorch/executorch/blob/main/build/test_ios.sh), whether it'd shed some light on how to setup ExecuTorch on a Mac.

Thanks.

**Comment by byjlw** [comment]
Tried to run the command. It failed. I cleaned things up and tried again. Failed with the same error.

`ERROR: Command errored out with exit status 1:
     command: /Users/byjlw/Documents/source/executorch/build/executorch/.venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nj/3xwfv5_55457s6gcrk5r8r6r0000gn/T/pip-req-build-tmh16uaa/setup.py'"'"'; __file__='"'"'/private/var/folders/nj/3xwfv5_55457s6gcrk5r8r6r0000gn/T/pip-req-build-tmh16uaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nj/3xwfv5_55457s6gcrk5r8r6r0000gn/T/pip-pip-egg-info-gfl_ubr5
         cwd: /private/var/folders/nj/3xwfv5_55457s6gcrk5r8r6r0000gn/T/pip-req-build-tmh16uaa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nj/3xwfv5_55457s6gcrk5r8r6r0000gn/T/pip-req-build-tmh16uaa/setup.py", line 10, in <module>
        from pybind11.setup_helpers import build_ext, Pybind11Extension
    ModuleNotFoundError: No module named 'pybind11'
    ----------------------------------------
WARNING: Discarding file:///Users/byjlw/Documents/source/executorch/build/executorch/backends/apple/coreml/runtime/inmemoryfs. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Users/byjlw/Documents/source/executorch/build/executorch/.venv/bin/python3 -m pip install --upgrade pip' command.
ExecuTorch: Failed to install inmemoryfs extension.

	** FAILED **
`

**Comment by dbort** [comment]
Do you have the full logs that lead up to that error? The top-level test_ios.sh script runs a bunch of other scripts, but I can't tell which one it's failing in from just the error. From the looks of it, we probably need to add `pybind11` to a requirements list somewhere.
