### ISSUE TITLE
Operator torch._ops.quantized_decomposed.quantize_per_tensor.default is not Aten Canonical

### ISSUE THREAD

**Issue by deahhh** [pytorch/executorch#2311]
Error after adding quantization.
```Python
from torch._export import capture_pre_autograd_graph
from torch.export import export, ExportedProgram
from torch.ao.quantization.quantize_pt2e import convert_pt2e, prepare_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
        get_symmetric_quantization_config,
        XNNPACKQuantizer,
    )
import torch

m = FasterNet(T0, 2)
m.eval()
example_args = (torch.randn(1, 1, 224, 224),)

pre_autograd_aten_dialect = capture_pre_autograd_graph(m, example_args)

# Optionally do quantization:
quantizer = XNNPACKQuantizer().set_global(get_symmetric_quantization_config())
pre_autograd_aten_dialect = convert_pt2e(prepare_pt2e(pre_autograd_aten_dialect, quantizer))

aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)

# Optionally do delegation:
# edge_program = edge_program.to_backend(CustomBackendPartitioner)

executorch_program: exir.ExecutorchProgramManager = edge_program.to_executorch(
    exir.ExecutorchBackendConfig(
        passes=[],  # User-defined passes
    )
)

with open("mobilenet_v2.pte", "wb") as file:
    file.write(executorch_program.buffer)
```

output:
```
Traceback (most recent call last):
  File "/data/work/cardDec/draft2.py", line 25, in <module>
    edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)
  File "/home/han/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 600, in to_edge
    EXIRATenDialectVerifier()(program.graph_module)
  File "/home/han/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_export/verifier.py", line 58, in __call__
    self.check_valid(gm)
  File "/home/han/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_export/verifier.py", line 117, in check_valid
    self.check_valid_op(node.target)
  File "/home/han/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_export/verifier.py", line 166, in check_valid_op
    raise SpecViolationError(
torch._export.verifier.SpecViolationError: Operator torch._ops.quantized_decomposed.quantize_per_tensor.default is not Aten Canonical.
```

**Comment by bob020416** [comment]
I'm having similar problem with trying to save a pretrained MobileNet model :

```
raise SpecViolationError(
torch._export.verifier.SpecViolationError: Operator torch._ops.aten._native_batch_norm_legit_functional.default is not Aten Canonical.
```

**Comment by deahhh** [comment]
@bob020416
Do you use `m.eval()` ?

**Comment by bob020416** [comment]
Damn.. you save my hoemwork, and for your situation i think if you don't do quantization,it can work

**Comment by deahhh** [comment]
> Damn.. you save my hoemwork, and for your situation i think if you don't do quantization,it can work

Yes, it does. Well, it's better with quantization for speed.

**Comment by tarun292** [comment]
@deahhh are you still interesting in getting this issue addressed? If so can you please repro on the latest release of ExecuTorch (0.5.0) and let us know how it goes.

**Comment by mergennachin** [comment]
@claude 

Convert this code to latest API and usage 

```
from torch._export import capture_pre_autograd_graph
from torch.export import export, ExportedProgram
from torch.ao.quantization.quantize_pt2e import convert_pt2e, prepare_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
        get_symmetric_quantization_config,
        XNNPACKQuantizer,
    )
import torch

m = FasterNet(T0, 2)
m.eval()
example_args = (torch.randn(1, 1, 224, 224),)

pre_autograd_aten_dialect = capture_pre_autograd_graph(m, example_args)

# Optionally do quantization:
quantizer = XNNPACKQuantizer().set_global(get_symmetric_quantization_config())
pre_autograd_aten_dialect = convert_pt2e(prepare_pt2e(pre_autograd_aten_dialect, quantizer))

aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)

# Optionally do delegation:
# edge_program = edge_program.to_backend(CustomBackendPartitioner)

executorch_program: exir.ExecutorchProgramManager = edge_program.to_executorch(
    exir.ExecutorchBackendConfig(
        passes=[],  # User-defined passes
    )
)

with open("mobilenet_v2.pte", "wb") as file:
    file.write(executorch_program.buffer)
```
