### ISSUE TITLE
Unknown target `generated_lib_all_ops` from package `root//kernels/portable`.

### ISSUE THREAD

**Issue by ChristophKarlHeck** [pytorch/executorch#2342]
Hi,

I am working with the current main branch and building the targets with the following command (described here: https://pytorch.org/executorch/main/runtime-build-and-cross-compilation.html):
```
cmake -DBUCK2=buck2 ..
```
raised the following issue:
```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- executorch: Generating source lists
-- executorch: Generating source file list /home/chris/et-tut-1/executorch/cmake-out/executorch_srcs.cmake
Error while generating /home/chris/et-tut-1/executorch/cmake-out/executorch_srcs.cmake. Exit code: 1
Output:

Error:
Traceback (most recent call last):
  File "/home/chris/et-tut-1/executorch/build/extract_sources.py", line 79, in run
    cp: subprocess.CompletedProcess = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/buck2', 'cquery', "inputs(deps('//kernels/portable:generated_lib_all_ops'))"]' returned non-zero exit status 3.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/et-tut-1/executorch/build/extract_sources.py", line 235, in <module>
    main()
  File "/home/chris/et-tut-1/executorch/build/extract_sources.py", line 220, in main
    target_to_srcs[name] = sorted(target.get_sources(graph, runner))
  File "/home/chris/et-tut-1/executorch/build/extract_sources.py", line 133, in get_sources
    sources: set[str] = set(runner.run(["cquery", query]))
  File "/home/chris/et-tut-1/executorch/build/extract_sources.py", line 84, in run
    raise RuntimeError(ex.stderr.decode("utf-8")) from ex
RuntimeError: [2024-03-11T08:46:51.868+01:00] Build ID: f094cc89-c697-4e7d-bf96-c50319c6eb9a
Command failed: 
Unknown target `generated_lib_all_ops` from package `root//kernels/portable`.
Did you mean one of the 46 targets in root//kernels/portable:TARGETS?
Maybe you meant one of these similar targets?
  root//kernels/portable:generated_lib


CMake Error at build/Utils.cmake:116 (message):
  executorch: source list generation failed
Call Stack (most recent call first):
  CMakeLists.txt:181 (extract_sources)


-- Configuring incomplete, errors occurred!
```
I solved it using the attached patch file on executorch/kernels/portable/targets.bzl file!

Cheers,
Christoph
[targets_patch.txt](https://github.com/pytorch/executorch/files/14555958/targets_patch.txt)

**Comment by larryliu0820** [comment]
I can't repro the error. Though the documentation needs some update for sure. Let me update it and we can close this issue.

**Comment by Gasoonjia** [comment]
Thanks for sharing your observation with us!
Yes, we will no longer make our examples and commands depend on buck2 and will get rid of them in our documentation as well as GitHub readme in the next release, which may help you and other valuable users. 
For your specific issue, let me try to reproduce it can give you a better response

**Comment by ChristophKarlHeck** [comment]
Hi guys,
Thank you for the response :)! I haven't tested it with the current v0.2.0 version, so I cannot say anything about the current behavior. @Gasoonjia, if you want to reproduce it, take the script build_et_libs.sh from (https://github.com/ChristophKarlHeck/mbed-torch-fusion-os/blob/main/utils/scripts/build_et_libs.sh) and uncomment line 65. There, you also see the version I used of ExecuTorch.
Cheers,
Christoph
