### ISSUE TITLE
nn.BatchNorm2d is not supported at exir.to_edge

### ISSUE THREAD

**Issue by kenzhang1118** [pytorch/executorch#2389]
When module includes nn.BatchNorm2d, exir.to_edge generates this error:

Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/my_test.py", line 347, in <module>
    edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/executorch/exir/program/_program.py", line 600, in to_edge
    EXIRATenDialectVerifier()(program.graph_module)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 58, in __call__
    self.check_valid(gm)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 117, in check_valid
    self.check_valid_op(node.target)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 166, in check_valid_op
    raise SpecViolationError(
torch._export.verifier.SpecViolationError: Operator torch._ops.aten._native_batch_norm_legit_functional.default is not Aten Canonical.

**Comment by cccclai** [comment]
Does it work if we turn off the ir validation?
```
        program_without_delegates = to_edge(
            aten_dialect,
            compile_config=exir.EdgeCompileConfig(
                _check_ir_validity=False,
            ),
        )
```
cc: @larryliu0820

**Comment by kenzhang1118** [comment]
I tried both:
**1. Turn off validation:**
Here is my code:
example_args = (torch.randn(1, 10, 1, 48, 48),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(SimpleModel(), example_args)
aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: exir.EdgeProgramManager = exir.to_edge(
            aten_dialect,
            compile_config=exir.EdgeCompileConfig(
                _check_ir_validity=False,
            ),
)

It still has error as below:
Traceback (most recent call last):
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/torch/fx/passes/infra/pass_manager.py", line 270, in __call__
    res = fn(module)
          ^^^^^^^^^^
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/torch/fx/passes/infra/pass_base.py", line 41, in __call__
    self.ensures(graph_module)
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/executorch/exir/passes/__init__.py", line 311, in ensures
    raise RuntimeError(f"Missing out variants: {self.missing_out_vars}")
RuntimeError: Missing out variants: {'aten::_native_batch_norm_legit_functional'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xiaokz/executorch/./my_test.py", line 347, in <module>
    executorch_program: exir.ExecutorchProgramManager = edge_program.to_executorch(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/executorch/exir/program/_program.py", line 784, in to_executorch
    new_prog = program._transform(*edge_to_executorch_passes(config))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/torch/export/exported_program.py", line 569, in _transform
    res = pm(self.graph_module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaokz/executorch/.executorch/lib/python3.11/site-packages/torch/fx/passes/infra/pass_manager.py", line 296, in __call__
    raise Exception(msg) from e
Exception: An error occurred when running the 'ToOutVarPass' pass after the following passes: ['SpecPropPass', 'EdgeToBackendOpsPass', 'RemoveAssertAsyncPass', 'HintBasedSymShapeEvalPass']
(.executorch) (base) xiaokz@bcd07466b662 executorch % python3 ./my_test.py

**2. Turn off autograd:**
example_args = (torch.randn(1, 10, 1, 48, 48),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(SimpleModel(), example_args)

with torch.no_grad():
    aten_dialect: ExportedProgram  = torch.export(pre_autograd_aten_dialect, example_args)

It has error as below:
Traceback (most recent call last):
  File "/Users/xiaokz/executorch/./my_test.py", line 334, in <module>
    aten_dialect: ExportedProgram  = torch.export(pre_autograd_aten_dialect, example_args)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

**Comment by cccclai** [comment]
oh you'd need `ExportedProgram = torch.export.export(pre_autograd_aten_dialect, example_args)`

**Comment by kenzhang1118** [comment]
looks like the autograd is not turned off
with torch.no_grad():
  aten_dialect: ExportedProgram = torch.export.export(pre_autograd_aten_dialect, example_args)

Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/./my_test.py", line 349, in <module>
    edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/executorch/exir/program/_program.py", line 600, in to_edge
    EXIRATenDialectVerifier()(program.graph_module)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 58, in __call__
    self.check_valid(gm)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 117, in check_valid
    self.check_valid_op(node.target)
  File "/home/ANT.AMAZON.COM/xiaokz/executorch/executorch/.executorch/lib/python3.11/site-packages/torch/_export/verifier.py", line 166, in check_valid_op
    raise SpecViolationError(
torch._export.verifier.SpecViolationError: Operator torch._ops.aten._native_batch_norm_legit_functional.default is not Aten Canonical.

**Comment by cccclai** [comment]
can you please share more code including the batchnorm, just so we can repro on our side?

**Comment by kenzhang1118** [comment]
class Test_Block(nn.Module):
    def __init__(self):
        super(Test_Block, self).__init__()
        out_channels = 32
        self.s = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3, 3), stride=(2, 2), padding=1, bias=False)
        self.bn_s = nn.BatchNorm2d(out_channels, momentum = 0.01, eps = 0.001)

    def forward(self, x):
        s_out = self.s(x)
        s_bn_out = self.bn_s(s_out)
        x = s_bn_out
        return x
example_args = (torch.randn(1, 3, 32, 32),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(Test_Block(), example_args)
aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: exir.EdgeProgramManager = exir.to_edge(
            aten_dialect)

**Comment by kenzhang1118** [comment]
problem is resolved after adding EagerMode, thanks for the help

**Comment by kenzhang1118** [comment]
Not sure why EagerModelBase helps that, but we can go with that for now. Thanks for the time!
