### ISSUE TITLE
ModuleNotFoundError: No module named 'executorch.extension.pytree.pybindings'

### ISSUE THREAD

**Issue by CHNtentes** [pytorch/executorch#2486]
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\>import executorch.exir as exir
Traceback (most recent call last):
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/extension/pytree/__init__.py", line 26, in <module>
    from executorch.extension.pytree.pybindings import (
ModuleNotFoundError: No module named 'executorch.extension.pytree.pybindings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/__init__.py", line 9, in <module>
    from executorch.exir.capture import (
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/capture/__init__.py", line 9, in <module>
    from executorch.exir.capture._capture import (
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/capture/_capture.py", line 15, in <module>
    from executorch.exir.capture._config import CaptureConfig
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/capture/_config.py", line 12, in <module>
    from executorch.exir.passes import MemoryPlanningPass, ToOutVarPass
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/passes/__init__.py", line 19, in <module>
    from executorch.exir import control_flow, memory, memory_planning
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/control_flow.py", line 58, in <module>
    from executorch.exir.tracer import (
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/exir/tracer.py", line 27, in <module>
    import executorch.extension.pytree as ex_pytree
  File "/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/executorch/extension/pytree/__init__.py", line 40, in <module>
    from torch.utils._pytree import (
ImportError: cannot import name 'treespec_dumps' from 'torch.utils._pytree' (/home/v2x/miniconda3/envs/ComfyUI/lib/python3.8/site-packages/torch/utils/_pytree.py)

**Comment by CHNtentes** [comment]
I can `import executorch` though. Not sure what the issue is here.

**Comment by JacobSzwejbka** [comment]
@larryliu0820 can you take a look at this

**Comment by JacobSzwejbka** [comment]
Seems like we might just need to add pytree to the oss pybindings build. Seems strange it hasn't popped up before. cc @lucylq.

**Comment by larryliu0820** [comment]
> @larryliu0820 can you take a look at this

@JacobSzwejbka after a second look, it seems executorch/extension/pytree/ is there and the issue is on torch.

@CHNtentes can you try reinstall torch nightly? You can run ./install_requirements.sh

**Comment by CHNtentes** [comment]
> > @larryliu0820 can you take a look at this
> 
> @JacobSzwejbka after a second look, it seems executorch/extension/pytree/ is there and the issue is on torch.
> 
> @CHNtentes can you try reinstall torch nightly? You can run ./install_requirements.sh

Yeah, it seems the issue comes from torch version. After reinstalling the import is working. Thanks for help.
