### ISSUE TITLE
Can't run examples ExecuTorch

### ISSUE THREAD

**Issue by ondeviceml** [pytorch/executorch#2618]
Hi ExecuTorch team, 

I've tried it a couple of times and I am just not able to run the examples at all. Following the steps listed here https://pytorch.org/executorch/stable/getting-started-setup.html: 

```
git clone https://github.com/pytorch/executorch.git

cd executorch
git submodule sync
git submodule update --init

python3 -m venv .executorch
source .executorch/bin/activate

./install_requirements.sh
bash /home/ondevice/code/executorch/build/install_flatc.sh

python3 -m examples.portable.scripts.export --model_name="add"

```

This errors out with 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/ondevice/code/executorch/examples/portable/__init__.py", line 7, in <module>
    from .utils import export_to_edge, export_to_exec_prog, save_pte_program
  File "/home/ondevice/code/executorch/examples/portable/utils.py", line 12, in <module>
    import executorch.exir as exir
ModuleNotFoundError: No module named 'executorch'

```

What am I doing wrong?

**Comment by salykovaa** [comment]
@ondeviceml 
try to run
```
python -m pip install setuptools --upgrade
```
before
```
./install_requirements.sh
```
Did this solve the problem?

**Comment by ondeviceml** [comment]
Thank you, @salykovaa. Was on pyenv as I saw that as supported through the documentation but yes switching to conda fixed the issue. 

```
Or alternatively use a Python virtual environment:

python3 -m venv .executorch
source .executorch/bin/activate
```

**Comment by JacobSzwejbka** [comment]
Taking a look

**Comment by orionr** [comment]
I wasa able to get things to work with virtualenv - just FYI

**Comment by orionr** [comment]
The older virtualenv (vs venv) seems to work

```
python3 -m pip install --user virtualenv
python3 -m virtualenv venv
source venv/bin/activate
git clone --branch release/0.2 https://github.com/pytorch/executorch.git
cd executorch
git submodule sync
git submodule update --init

./install_requirements.sh
./build/install_flatc.sh
python3 -m examples.portable.scripts.export --model_name="add"
```

But that still doesn't let us know if native venv itself works.

The output:

```
% python3 -m examples.portable.scripts.export --model_name="add"
[INFO 2024-04-07 16:10:55,938 utils.py:41] Core ATen graph:
graph():
    %arg0_1 : [num_users=3] = placeholder[target=arg0_1]
    %arg1_1 : [num_users=1] = placeholder[target=arg1_1]
    %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, %arg1_1), kwargs = {})
    %add_1 : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%add, %arg0_1), kwargs = {})
    %add_2 : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%add_1, %arg0_1), kwargs = {})
    %add_3 : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%add_2, %add_2), kwargs = {})
    return (add_3,)
[INFO 2024-04-07 16:10:55,961 utils.py:61] Exported graph:
graph():
    %arg0_1 : [num_users=3] = placeholder[target=arg0_1]
    %arg1_1 : [num_users=1] = placeholder[target=arg1_1]
    %aten_add_tensor : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten.add.Tensor](args = (%arg0_1, %arg1_1), kwargs = {})
    %aten_add_tensor_1 : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten.add.Tensor](args = (%aten_add_tensor, %arg0_1), kwargs = {})
    %aten_add_tensor_2 : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten.add.Tensor](args = (%aten_add_tensor_1, %arg0_1), kwargs = {})
    %aten_add_tensor_3 : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten.add.Tensor](args = (%aten_add_tensor_2, %aten_add_tensor_2), kwargs = {})
    return (aten_add_tensor_3,)
[INFO 2024-04-07 16:10:56,016 utils.py:112] Saved exported program to ./add.pte
```

cc @byjlw
