### ISSUE TITLE
no attribute 'dequantize_per_channel_group'. Did you mean: 'dequantize_per_channel'?

### ISSUE THREAD

**Issue by ondeviceml** [pytorch/executorch#2626]
Following the tutorial here to lower mv2 to xnnpack: https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html

After running this 
`python -m examples.xnnpack.aot_compiler --model_name="mv2" --delegate`

I get the following error. Trying different models eg mv3 errors with the same issue. 

```
(executorch) *[main][~/code/executorch]$ python -m examples.xnnpack.aot_compiler --model_name="mv2" --delegate
Traceback (most recent call last):
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/dialects/_ops.py", line 100, in __getattr__
    parent_packet = getattr(self._op_namespace, op_name)
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_ops.py", line 927, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'quantized_decomposed' object has no attribute 'dequantize_per_channel_group'. Did you mean: 'dequantize_per_channel'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ondeviceml/code/executorch/examples/xnnpack/aot_compiler.py", line 14, in <module>
    from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/xnnpack/__init__.py", line 8, in <module>
    from .partition.xnnpack_partitioner import (
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/xnnpack/partition/xnnpack_partitioner.py", line 26, in <module>
    from executorch.backends.xnnpack.passes.fuse_batch_norm_with_conv import (
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/xnnpack/passes/__init__.py", line 12, in <module>
    from executorch.backends.xnnpack.passes.conv1d_unsqueeze_pass import Conv1dUnsqueezePass
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/xnnpack/passes/conv1d_unsqueeze_pass.py", line 11, in <module>
    from executorch.backends.xnnpack.utils.quant_utils import is_dequant, is_quant
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/xnnpack/utils/quant_utils.py", line 14, in <module>
    exir_ops.edge.quantized_decomposed.dequantize_per_channel_group.default,
  File "/Users/ondeviceml/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/dialects/_ops.py", line 104, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'edge.quantized_decomposed' object has no attribute 'dequantize_per_channel_group'. Did you mean: 'dequantize_per_channel'?
(executorch) *[main][~/code/executorch]$
```

**Comment by salykovaa** [comment]
hi @ondeviceml 
the main branch is under active developement and may be unstable. could you try the stable and verified branch? this should resolve the problem
```
git clone --branch v0.1.0 https://github.com/pytorch/executorch.git
```

**Comment by ondeviceml** [comment]
Thank you, @salykovaa. I was hoping to try some of the new features like the partitioners but yeah I guess I need to try that branch. Is that what you are doing? I thought given that it's from ~6 months ago it would be better to go ahead with the newer one.

**Comment by salykovaa** [comment]
@ondeviceml 
temporal solution would be
```
git clone https://github.com/pytorch/executorch.git
git checkout 725c590
```

**Comment by ondeviceml** [comment]
Thank you again, @salykovaa. I guess would have worked but triton doesn't install on macs :( 

> I don't understand the issue/drama here. Triton is only supported on Linux, as mentioned in README.md. PyPI page has wheels for Python 3.6 - 3.11 on Linux. We don't have any windows CI machine. We're not Java; we're a small team at OpenAI working on this project, and we have busy jobs working on compiler optimizations and stability improvements for LLMs. All the extra community management work is done in our free time. The project is open-source; if you think the documentation is inaccurate or the cibuildwheelcommand is wrong, you are free to submit a PR.

**Comment by salykovaa** [comment]
@ondeviceml can you try
```
git checkout viable/strict
```
does this work?

**Comment by JacobSzwejbka** [comment]
Ah yeah the triton stuff is a known recent issue. We were trying to fix over the weekend. I think its fixed as of right now, but lots of other stuff is broken on master right now. Can you check back tomorrow where hopefully CI will be stable. @ondeviceml
