### ISSUE TITLE
Build failed on main branch

### ISSUE THREAD

**Issue by mhs4670go** [pytorch/executorch#2867]
Hello. I'm trying to install an executorch on the main branch.

My ubuntu version is 20.04 and I installed python version 3.10.4 with pyenv.

The commit hash of executorch is 8d8fe09fb.

```bash
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install -U pip wheel setuptools

$ git submodule sync
$ git submodule update --init
$ ./install_requirements.sh

Building wheels for collected packages: executorch
  Running command Building wheel for executorch (pyproject.toml)
  running bdist_wheel
  running build
  command options for 'CustomBuild':
    build_base = pip-out
    build_purelib = pip-out/lib
    build_platlib = pip-out/lib.linux-x86_64-cpython-310
    build_lib = pip-out/lib.linux-x86_64-cpython-310
    build_scripts = pip-out/scripts-3.10
    build_temp = pip-out/temp.linux-x86_64-cpython-310
    plat_name = linux-x86_64
    compiler = None
    parallel = 19
    debug = None
    force = None
    executable = /home/seongwoo/circle-exir/.venv/bin/python
  creating /home/seongwoo/circle-exir/submodules/executorch/pip-out
  creating /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310
  creating /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out
  deleting /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/CMakeCache.txt
  cmake -S /home/seongwoo/circle-exir/submodules/executorch -B /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out -DBUCK2= -DPYTHON_EXECUTABLE=/home/seongwoo/circle-exir/.venv/bin/python -DCMAKE_PREFIX_PATH=/home/seongwoo/circle-exir/.venv/lib/python3.10/site-packages -DCMAKE_BUILD_TYPE=Release -DEXECUTORCH_ENABLE_LOGGING=ON -DEXECUTORCH_LOG_LEVEL=Info
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE
  -- Downloading FXdiv to /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/FXdiv-source (define FXDIV_SOURCE_DIR to avoid it)
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/FXdiv-download
  [ 11%] Creating directories for 'fxdiv'
  [ 22%] Performing download step (git clone) for 'fxdiv'
  Cloning into 'FXdiv-source'...
  Already on 'master'
  Your branch is up to date with 'origin/master'.
  [ 33%] Performing update step for 'fxdiv'
  [ 44%] No patch step for 'fxdiv'
  [ 55%] No configure step for 'fxdiv'
  [ 66%] No build step for 'fxdiv'
  [ 77%] No install step for 'fxdiv'
  [ 88%] No test step for 'fxdiv'
  [100%] Completed 'fxdiv'
  [100%] Built target fxdiv
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Using python executable '/home/seongwoo/circle-exir/.venv/bin/python'
  -- Resolved buck2 as /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3.
  -- executorch: Generating source lists
  -- executorch: Generating source file list /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake
  Error while generating /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/home/seongwoo/circle-exir/submodules/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/home/seongwoo/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/seongwoo/circle-exir/submodules/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/home/seongwoo/circle-exir/submodules/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/home/seongwoo/circle-exir/submodules/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/home/seongwoo/circle-exir/submodules/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      0: Failed to stat `/home/seongwoo/circle-exir/submodules/executorch/buck-out/v2`
      1: ENOENT: No such file or directory


  CMake Error at build/Utils.cmake:161 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:261 (extract_sources)


  -- Configuring incomplete, errors occurred!
  error: command '/home/seongwoo/circle-exir/.venv/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/seongwoo/circle-exir/.venv/bin/python /home/seongwoo/circle-exir/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpgotpvfaj
  cwd: /home/seongwoo/circle-exir/submodules/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: Could not build wheels for executorch, which is required to install pyproject.toml-based projects
```

I can't sort it out properly.. Could you guess the problem of this?

**Comment by orgicus** [comment]
Hi @mhs4670go I've just tried executorch today for the first time and ran into a build error myself (on OSX through).

Quickly skimming through the error it seems to complain about a path not existing:
```
...
 Caused by:
      0: Failed to stat `/home/seongwoo/circle-exir/submodules/executorch/buck-out/v2`
      1: ENOENT: No such file or directory
...
```

I'd start by double checking if that path is valid.
I suspect it is based on this line:
` Resolved buck2 as /home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3.`

However this line failed:

```
  subprocess.CalledProcessError: Command '['/home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

```
hopefully you can try to run the command manually, outside of python wheel building to verify paths and arguments directly.

e.g.
```bash
/home/seongwoo/circle-exir/submodules/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3 cquery inputs(deps('//runtime/executor:program'))
```
(I'd also try inputs(deps("//runtime/executor:program")) just in case).

This is a bit of guess work on my side without a Ubuntu system to easily test, so do take the above with a pinch of salt.
I do hope this helps you trouble shoot the issue.

(If for some reason buck2 doesn't run the https://pytorch.org/executorch/stable/getting-started-setup guide mentions a specific prebuilt version of buck2 you can try: https://github.com/facebook/buck2/releases/tag/2023-07-18 . You'll need `zstd` (pip module) to unpack, e.g. `zstd -d buck2-x86_64-unknown-linux-gnu.zst` (replace with the version of linux you need of course and don't forget to make the unzipped file executable and add to `$PATH`)).

**Comment by mhs4670go** [comment]
@orgicus Thank you for the detail explanation!

> hopefully you can try to run the command manually, outside of python wheel building to verify paths and arguments directly.

Actually, I had done that at that time but it didn't work well where buck complained "Error validating working directory".

As you said, when I try with buck2 2023-07-18 version, the error happened just like #2622. Seems I have to use buck version as `submodules/executorch/.ci/docker/ci_commit_pins/buck2.txt` says - 2024-02-15.

I just guessed my working directory is something wrong and I retried the commands after removing all the directory and cloned again, which worked:) I think my directory somehow(?) had gotten dirty..

Anyway, thanks again for your guide. 

I'll just write down the commands I ran for the others who suffer from similar problem and close the issue. It's almost same with the tutorial document though.

Ubuntu version: 20.04
Python version with pyenv: 3.10.4
Commit hash: 1e8c0ff
Commands
```bash
cd executorch

python -m venv .venv
source .venv/bin/activate
# must be updated, got errors otherwise
pip install -U pip wheel setuptools

git submodule sync
git submodule update --init
./install_requirements.sh
```

**Comment by Wangbk-dl** [comment]
I've met the same problem and solve it by the following command:

`/tmp/buck2 clean`

`/tmp/buck2 kill`

the problem may be caused by the uncleaned buck2 process.

**Comment by utkusaglm** [comment]
> I've met the same problem and solve it by the following command:
> 
> `/tmp/buck2 clean`
> 
> `/tmp/buck2 kill`
> 
> the problem may be caused by the uncleaned buck2 process.

For others, if this doesn't work for you, you can first find the ids with `ps aux | grep buck2`, then kill them by `kill -9 <id>`
