### ISSUE TITLE
Tagging ConstantArgument in delegation

### ISSUE THREAD

**Issue by mhs4670go** [pytorch/executorch#3278]
Hello.

I'm trying to convert below module to my backend binary.

```python
import torch
N_HEADS = 4
DIM = 16
MAX_SEQ_LEN = 8

def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
    theta_numerator = torch.arange(0, dim, 2)[: (dim // 2)].float()
    freqs = 1.0 / (theta ** (theta_numerator / dim))
    t = torch.arange(end, device=freqs.device)  # type: ignore
    freqs = torch.outer(t, freqs).float()  # type: ignore
    freqs_cos = torch.cos(freqs)
    freqs_sin = torch.sin(freqs)
    return freqs_cos, freqs_sin

class PrecomputeFreqsCIS(torch.nn.Module):
    def __init__(self):
        super().__init__()
        freqs_cos, freqs_sin = precompute_freqs_cis(
            DIM // N_HEADS,
            MAX_SEQ_LEN * 2,
        )
        self.register_buffer("freqs_cos", freqs_cos, persistent=False)
        self.register_buffer("freqs_sin", freqs_sin, persistent=False)

    # These `start_pos` and `seq_len` inputs seems wrong
    def forward(self, start_pos: int, seq_len: int = 1):
        freqs_cos = self.freqs_cos[start_pos : start_pos + seq_len]
        freqs_sin = self.freqs_sin[start_pos : start_pos + seq_len]
        return (
            freqs_cos,
            freqs_sin,
        )

    def get_example_inputs(self):
        start_pos = 2
        seq_len = 1
        return (
            start_pos,
            seq_len,
        )

```

But, below error happened.

```bash
Traceback (most recent call last):
  File "/home/seongwoo/-exir/utils/utils.py", line 18, in convert_exported_module_to_backend
    module_edge = module_edge.to_backend(MyPartitioner())
  File "/home/seongwoo/-exir/.venv/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 813, in to_backend
    new_edge_programs[name] = to_backend(program, partitioner)
  File "/home/seongwoo/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/seongwoo/-exir/.venv/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 390, in _
    new_signature, new_state_dict, new_constants = _get_new_signature(
  File "/home/seongwoo/-exir/.venv/lib/python3.10/site-packages/executorch/exir/lowered_backend_module.py", line 468, in _get_new_signature
    assert tag is not None
AssertionError
```

The graph signature of the module is like below.
```
ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg0_1'), target='freqs_cos', persistent=False), 
InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg1_1'), target='freqs_sin', persistent=False), 
InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=ConstantArgument(value=2), target=None, persistent=None), 
InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=ConstantArgument(value=1), target=None, persistent=None)], 
output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='aten_slice_copy_tensor'), target=None), 
OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='aten_slice_copy_tensor_1'), target=None)])
```

And, the error was raised because the `ConstantArgument` inputs were not tagged.
```
InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=ConstantArgument(value=2), target=None, persistent=None), 
InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=ConstantArgument(value=1), target=None, persistent=None)],
```

I can tag buffers and parameters with `tag_constant_data` API but how can I tag the constant argument? Or, Am I doing something wrong?

**Comment by cccclai** [comment]
From `PrecomputeFreqsCIS`, it looks like `seq_len` is real user input, what would you like to do with the constant data? Since it's user input, I expect it to be also an input to your backend?

**Comment by mhs4670go** [comment]
@cccclai Thank you for the comment. As you said, it's gonna be user input. I just thought that example input data type could be built-in integer for the user input. But seems that it should be tensors. So I changed them to tensors.

```python
# int -> torch.Tensor
def forward(self, start_pos: torch.Tensor, seq_len: torch.Tensor):
        freqs_cos = self.freqs_cos[start_pos : start_pos + seq_len]
        freqs_sin = self.freqs_sin[start_pos : start_pos + seq_len]
        return (
            freqs_cos,
            freqs_sin,
        )

    def get_example_inputs(self):
        start_pos = torch.tensor(2, dtype=torch.int32)
        seq_len = torch.tensor(1, dtype=torch.int32)
        return (
            start_pos, seq_len,
        )
```

Well, nonetheless, it raised another issue.
```
torch._dynamo.exc.Unsupported: Dynamic slicing on data-dependent value is not supported

from user code:
   File "/home/seongwoo/exir/test/modules/net/PrecomputeFreqsCIS.py", line 64, in forward
    freqs_cos = self.freqs_cos[start_pos : start_pos + seq_len]
```

Seems that it was because of the dynamic slicing. So, I just removed `seq_len` since it is almost likely 1 in the inference.

```python
# seq_len removed
def forward(self, start_pos: torch.Tensor):
        freqs_cos = self.freqs_cos[start_pos]
        freqs_sin = self.freqs_sin[start_pos]
        return (
            freqs_cos,
            freqs_sin,
        )

    def get_example_inputs(self):
        start_pos = torch.tensor(2, dtype=torch.int32)
        return (
            start_pos,
        )
```

Then, another error happened and I don't have any clue for resolving this.
```
torch._dynamo.exc.UserError: Tried to use data-dependent value in the subsequent computation. This can happen when we encounter unbounded dynamic value that is unknown during tracing time.  You will need to explicitly give hint to the compiler. Please take a look at constrain_as_value OR constrain_as_size APIs.  Could not guard on data-dependent expression u0 (unhinted: u0).  (Size-like symbols: none)
```

I tried two things.
```python
# 1. use `_constrain_as_size` -> same error occurred
torch._constrain_as_size(start_pos, min=0, max=MAX_SEQ_LEN - 1)
freqs_cos = self.freqs_cos[start_pos]

# 2. give random input
def get_example_inputs(self):
        # start_pos = torch.tensor(2, dtype=torch.int32)
        start_pos = torch.randn(1).to(torch.int32) 
```

Dynamo didn't complain anything with the second approach. But, since I haven't support `aten.index.Tensor` operator for my backend yet, the conversion didn't make it. 

It would be very helpful if you have any idea to relieve these issues or apply some workaround.

**Comment by cccclai** [comment]
Hmm I think depending on your code implementation, it can either be tensor or int...I'm not quite sure the goal for your backend. Are you trying to lower some operators to your backend?

**Comment by mhs4670go** [comment]
> Are you trying to lower some operators to your backend?

Yeah. Actually, I'm trying to lower the example [llama2 model](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/llama_transformer.py) to my backend. Before converting the whole model, I wanted to split it into smaller modules for the unittest purpose. But seems that some limitations exist when it comes to the input spec or module hiararchy. 

Anyway, I've relieved the issue by trying to convert bigger module, which doesn't have dynamic slicing or integer input. Thank you for the comments!
