### ISSUE TITLE
how to calculate the vocab_size of new model

### ISSUE THREAD

**Issue by l2002924700** [pytorch/executorch#3620]
hi, 
when I tried to introduce the "Blue LLM" model and evaluate its ppl, there is a mistake as follow:
Traceback (most recent call last):
  File "/home/ufoe/anaconda3/envs/linchao/bin/lm_eval", line 8, in <module>
    sys.exit(cli_evaluate())
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/__main__.py", line 341, in cli_evaluate
    results = evaluator.simple_evaluate(
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/evaluator.py", line 180, in simple_evaluate
    lm = lm_eval.api.registry.get_model(model).create_from_arg_string(
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/api/model.py", line 134, in create_from_arg_string
    return cls(**args, **args2)
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/models/huggingface.py", line 203, in __init__
    self._create_model(
  File "/home/ufoe/linchao/lm-evaluation-harness/lm_eval/models/huggingface.py", line 544, in _create_model
    self._model = self.AUTO_MODEL_CLASS.from_pretrained(
  File "/home/ufoe/anaconda3/envs/linchao/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ufoe/anaconda3/envs/linchao/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ufoe/anaconda3/envs/linchao/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/ufoe/anaconda3/envs/linchao/lib/python3.10/site-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/ufoe/anaconda3/envs/linchao/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 358, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([100008, 4096]) in "weight" (which has shape torch.Size([100096, 4096])), this look incorrect.

how to calculate the vocab_size?
thank you

**Comment by mergennachin** [comment]
Usually params.json has the vocabulary size. 

Cc @larryliu0820 @iseeyuan
