### ISSUE TITLE
llama model with coreml backend doesn't work on iphone 13 pro

### ISSUE THREAD

**Issue by seayoung1112** [pytorch/executorch#3712]
First, the same test worked fine on iphone 15/14, so it's very likely an issue on iphone 13

Test set up:

llama ExecuTorch ios app, built locally
iphone **13 pro**, ios version **17.4**

llama model was exported using the command:
`python -m examples.models.llama2.export_llama -c <model.ckpt> -p <model_params.json> --coreml --use_kv_cache`

The app crashed with the following error log:

> Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
> Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
> Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
> MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 3 try
> /Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Utility/MPSLibrary.mm, line 491: error 'MPSLibrary::MPSKey_Create internal error: Unable to get MPS kernel NDArrayVectorMatrixMultiply. Error: Compiler encountered an internal error
> '
> /Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Utility/MPSLibrary.mm:491: failed assertion `MPSLibrary::MPSKey_Create internal error: Unable to get MPS kernel NDArrayVectorMatrixMultiply. Error: Compiler encountered an internal error

**Comment by cymbalrush** [comment]
We are investigating the crash, @seayoung1112 could you please share the crash log.

**Comment by seayoung1112** [comment]
> We are investigating the crash, @seayoung1112 could you please share the crash log.

Sorry I didn't describe it clearly, it didn't crash, the app hangs there on the error and I have to close it manually. The only logs are what I added in the report

**Comment by YifanShenSZ** [comment]
Hi @cheerss, looks like for some reason the llama export script starts to pass fp16 to Core ML?

If it is ok to support only iOS16+ OS for you, then please modify [here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/lib/partitioner_lib.py#L67-L72)
```
     compile_specs = CoreMLBackend.generate_compile_specs(
         compute_precision=ct.precision(ct.precision.FLOAT16.value),
         # using `ComputeUnit.ALL` can increase the model load time, default to `ComputeUnit.CPU_AND_GPU`
         compute_unit=ct.ComputeUnit[ct.ComputeUnit.CPU_AND_GPU.name.upper()],
         model_type=CoreMLBackend.MODEL_TYPE.MODEL,
+       minimum_deployment_target=ct.target.iOS16,
     )
```

**Comment by cheerss** [comment]
@YifanShenSZ Wow, nice solution and  explaination. That's really works. Thanks a lot. While another problem emerges after the backend optimization process T_T:

```
Running MIL default pipeline: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 78/78 [00:00<00:00, 9429.21 passes/s]
Running MIL backend_mlprogram pipeline: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 22723.09 passes/s]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/somewhere/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File "/somewhere/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File "/somewhere/executorch/examples/models/llama2/export_llama_lib.py", line 307, in export_llama
    builder = _export_llama(modelname, args)
  File "/somewhere/executorch/examples/models/llama2/export_llama_lib.py", line 455, in _export_llama
    builder = builder_exported_to_edge.to_backend(partitioners).to_executorch()
  File "/somewhere/executorch/examples/models/llama2/builder.py", line 351, in to_backend
    self.edge_manager = self.edge_manager.to_backend(partitioner)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1166, in to_backend
    new_edge_programs[name] = to_backend(program, partitioner)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 384, in _
    tagged_graph_module = _partition_and_lower(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 299, in _partition_and_lower
    partitioned_module = _partition_and_lower_one_graph_module(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 230, in _partition_and_lower_one_graph_module
    lowered_submodule = to_backend(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 114, in _
    preprocess_result: PreprocessResult = cls.preprocess(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/apple/coreml/compiler/coreml_preprocess.py", line 367, in preprocess
    mlmodel = ct.convert(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/_converters_entry.py", line 581, in convert
    mlmodel = mil_convert(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/converter.py", line 188, in mil_convert
    return _mil_convert(model, convert_from, convert_to, ConverterRegistry, MLModel, compute_units, **kwargs)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/converter.py", line 212, in _mil_convert
    proto, mil_program = mil_convert_to_proto(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/converter.py", line 288, in mil_convert_to_proto
    prog = frontend_converter(model, **kwargs)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/converter.py", line 108, in __call__
    return load(*args, **kwargs)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/load.py", line 73, in load
    converter = TorchConverter(
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/converter.py", line 384, in __init__
    self.graph = InternalTorchIRGraph.from_exir(exir=loaded_model)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/internal_graph.py", line 524, in from_exir
    extract_inputs_from_exir_program(exported_program)
  File "/opt/anaconda3/envs/executorch/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/exir_utils.py", line 88, in extract_inputs_from_exir_program
    assert isinstance(val, torch.Tensor), "placeholder val must be a tensor or fake tensor"
AssertionError: placeholder val must be a tensor or fake tensor
```

**Comment by YifanShenSZ** [comment]
@cheerss There are 2 possible reasons I can guess of:
1. ExecuTorch may have some change since 0.2.0, that the model is partitioned differently thus something non-tensor is delegated to Core ML. Can you retry with ExecuTorch 0.2.0?
2. Your model may be different from the Llama model in ExecuTorch example, and contains some unsupported op in Core ML thus triggered partition. Can you verify by converting directly with [coremltools](https://github.com/apple/coremltools/releases/tag/7.2)? Here is an example
```
import torch
import torchvision
import executorch.exir

import coremltools as ct

torch_model = torchvision.models.vit_b_16(weights="IMAGENET1K_V1")

x = torch.rand((1, 3, 224, 224))
example_inputs = (x,)
exported_program_aten = torch.export.export(torch_model, example_inputs)
exported_program_edge = executorch.exir.to_edge(exported_program_aten)

coreml_model = ct.convert(exported_program_edge)
```

**Comment by jefflewis** [comment]
in released versions of my app, I've exported a model with coremltools and see this on _some_ devices some times. I am having a hard time finding what is using `NDArrayVectorMatrixMultiply` and why it doesn't happen reliably and only on some devices.
