### ISSUE TITLE
Error when running install_requirements.sh

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#3802]
Had a fresh clone of the repo and trying to set it up with the `install_requirements.sh` command. It works very well previously. But now I am seeing the following error? Seems something wrong with the buck2. 
```
  [ 66%] No test step for 'fxdiv'
  [ 77%] Completed 'fxdiv'
  [100%] Built target fxdiv
  -- Using python executable '/usr/bin/python3'
  -- Resolved buck2 as /staging/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284.
  -- Killing buck2 daemon
  -- executorch: Generating source lists
  -- executorch: Generating source file list /staging/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake
  Error while generating /staging/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/staging/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/usr/lib/python3.10/subprocess.py", line 526, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/staging/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/staging/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/staging/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/staging/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/staging/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      Buck appears to be running in a stale working directory This will likely lead to failed or slow builds. To remediate, restart Buck2.

```

**Comment by mergennachin** [comment]
Can you try `buck2 clean`?

**Comment by Jerry-Ge** [comment]
Got this figured out.

**Comment by qiaoli31** [comment]
I got same issue but I got "Command buck2 not found" when try `buck2 clean`. Any suggestion?

**Comment by hsyodyssey** [comment]
Thanks, this is useful

**Comment by daniil-lyakhov** [comment]
> I got same issue but I got "Command buck2 not found" when try `buck2 clean`. Any suggestion?

I found my buck2 bin in the `buck2-bin` directory in the root of the executorch repo, hopefully you will find your buck2 bin here too
