### ISSUE TITLE
Is there a way to run executorch as a git submodule?

### ISSUE THREAD

**Issue by rcontesti** [pytorch/executorch#3821]
Hi, I'm currently succesfully running the [getting started tutoral](https://pytorch.org/executorch/stable/getting-started-setup.html). Unfortunately I'm not able to run executorch as submodule outside of the executorch directory.

When I try to run `$python3 export_add.py` outside executorch directory I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/ruben/code/local_llm/add.py", line 25, in <module>
    executorch_program = edge_program.to_executorch()
  File "/home/ruben/code/local_llm/executorch/exir/program/_program.py", line 871, in to_executorch
    return ExecutorchProgramManager(
  File "/home/ruben/code/local_llm/executorch/exir/program/_program.py", line 925, in __init__
    self._pte_data: Cord = _serialize_pte_binary(
  File "/home/ruben/code/local_llm/executorch/exir/_serialize/_program.py", line 424, in serialize_pte_binary
    result: _FlatbufferResult = _program_json_to_flatbuffer(
  File "/home/ruben/code/local_llm/executorch/exir/_serialize/_flatbuffer.py", line 283, in _program_json_to_flatbuffer
    schema_info = _prepare_schema(
  File "/home/ruben/code/local_llm/executorch/exir/_serialize/_flatbuffer.py", line 156, in _prepare_schema
    schemas = _ResourceFiles([program_schema] + deps)
  File "/home/ruben/code/local_llm/executorch/exir/_serialize/_flatbuffer.py", line 113, in __init__
    self._files[name] = importlib.resources.read_binary(__package__, name)
  File "/home/ruben/anaconda3/envs/executorch/lib/python3.10/importlib/resources.py", line 88, in read_binary
    with open_binary(package, resource) as fp:
  File "/home/ruben/anaconda3/envs/executorch/lib/python3.10/importlib/resources.py", line 46, in open_binary
    return reader.open_resource(resource)
  File "/home/ruben/anaconda3/envs/executorch/lib/python3.10/importlib/abc.py", line 433, in open_resource
    return self.files().joinpath(resource).open('rb')
  File "/home/ruben/anaconda3/envs/executorch/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruben/code/local_llm/executorch/exir/_serialize/program.fbs'
```
Basically, it says that file `program.fbs` is missing. I searched the directory and that file is not part of the library nor is created in the process. Curious if somebody has been able to run it as a submodule. Many thanks!

**Comment by mergennachin** [comment]
@rcontesti 

This tutorial has a way to run nano-gpt and uses executorch as gitsubmodule.

https://pytorch.org/executorch/main/llm/getting-started.html

Do you wanna give it a shot? 

Cc @GregoryComer

**Comment by rcontesti** [comment]
Many thanks @mergennachin, I will give it a try today. PD: It seems that the process is quite ad hoc depending on the model
