### ISSUE TITLE
Got "Buck appears to be running in a stale working directory" when run install_requirements.sh

### ISSUE THREAD

**Issue by qiaoli31** [pytorch/executorch#4439]
### 🐛 Describe the bug

I'm using main branch and follow environment setup guide [here](https://pytorch.org/executorch/stable/getting-started-setup.html#environment-setup). When I run ./install_requirements.sh, I got follow errors.

```
  [100%] Completed 'fxdiv'
  [100%] Built target fxdiv
  -- Using python executable '/usr/local/home/user/miniconda3/envs/executorch/bin/python'
  -- Resolved buck2 as /usr/local/home/user/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284.
  -- Killing buck2 daemon
  -- executorch: Generating source lists
  -- executorch: Generating source file list /usr/local/home/user/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake
  Error while generating /usr/local/home/user/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/usr/local/home/user/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/usr/local/home/user/miniconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/usr/local/home/user/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/usr/local/home/user/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/usr/local/home/user/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/usr/local/home/user/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/usr/local/home/user/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      Buck appears to be running in a stale working directory This will likely lead to failed or slow builds. To remediate, restart Buck2.


  CMake Error at build/Utils.cmake:191 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:327 (extract_sources)home/user
```

I found [issues 3802](https://github.com/pytorch/executorch/issues/3802) but I got "Command buck2 not found" when try `buck2 clean`.

**Comment by mcr229** [comment]
@larryliu0820 @GregoryComer any ideas here?

**Comment by l3utterfly** [comment]
@mcr229 I had this issue before, kill the buck2 process, then re-build

`ps aux | grep buck`
`pkill -f buck`

**Comment by qiaoli31** [comment]
after deactivate and rebuild, it seems working now. Thanks!
