### ISSUE TITLE
./install_requirements.sh  Error

### ISSUE THREAD

**Issue by ChiuHsiungW** [pytorch/executorch#4480]
### 🐛 Describe the bug

The following is the error message when I execute ./install_requirements.sh
My operation process follows [https://pytorch.org/executorch/stable/getting-started-setup.html](url)

conda create -yn executorch python=3.10.0
conda activate executorch
git clone --branch v0.3.0 https://github.com/pytorch/executorch.git
cd executorch
git submodule sync
git submodule update --init
./install_requirements.sh

```      Error while generating /export/AI01home/justin_wang/Desktop/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/export/AI01home/justin_wang/Desktop/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/export/AI01home/justin_wang/anaconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/export/AI01home/justin_wang/Desktop/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/export/AI01home/justin_wang/Desktop/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/export/AI01home/justin_wang/Desktop/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/export/AI01home/justin_wang/Desktop/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/export/AI01home/justin_wang/Desktop/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      Buck appears to be running in a stale working directory This will likely lead to failed or slow builds. To remediate, restart Buck2.


  CMake Error at build/Utils.cmake:191 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:311 (extract_sources)


  -- Configuring incomplete, errors occurred!
  See also "/export/AI01home/justin_wang/Desktop/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/CMakeFiles/CMakeOutput.log".
  error: command '/usr/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /export/AI01home/justin_wang/anaconda3/envs/executorch/bin/python /export/AI01home/justin_wang/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpc9e7n1t1
  cwd: /export/AI01home/justin_wang/Desktop/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (executorch)



```

**Comment by tiger-of-shawn** [comment]
+1
