### ISSUE TITLE
[Llama] [Dynamic Shape] [Core ML Delegate] Do Not Delegate Symbol Manipulation

### ISSUE THREAD

**Issue by YifanShenSZ** [pytorch/executorch#4658]
### 🐛 Describe the bug

When export dynamic-shape llama2, in the attached [piece of the partitioned model](https://github.com/user-attachments/files/16568296/partitioned-model_piece-2.txt), there are symbol manipulations such as
```
add: "Sym(s0 + u156)" = _local_scalar_dense + sym_size
...
le_1: "Sym(s0 + u156 <= 128)" = add <= 128
```
Which came from dynamic shape check assertions in the [original model](https://github.com/user-attachments/files/16568298/original-model.txt)
```
add: "Sym(s0 + u156)" = _local_scalar_dense + sym_size
le_1: "Sym(s0 + u156 <= 128)" = add <= 128
_assert_scalar_2 = torch.ops.aten._assert_scalar.default(le_1, "Runtime assertion failed for expression s0 + u0 <= 128 on node 'le_27'");  le_1 = None
```
This leads to 2 problems:
1. Core ML does not support symbol itself as model io
2. `torch.ops.aten._assert_scalar.default` is scattered all over the program, which may lead to unwanted graph breaks

Imho:
1. These dynamic shape checks are very small, so doing them in executorch runtime may be more efficient than paying delegate overhead
2. All assertions may be done at the beginning of the program in executorch runtime, so the rest heavy computation can be delegated to Core ML as a whole graph

### Versions

Executorch main branch, commit hash `7cd96f71ce254c061df7666bb3654903c3c4306a`

**Comment by cccclai** [comment]
Discuss a bit, there are two action items
1. Convert symint etc to tensor, then they can be consumed by coreml IR.
2. Remove the assert in the model definition, this likely be removed for the batch prefill branch in llama transformer.

**Comment by YifanShenSZ** [comment]
cc @kimishpatel

**Comment by kimishpatel** [comment]
> Convert symint etc to tensor, then they can be consumed by coreml IR.

@YifanShenSZ do you know what is this intended for?

**Comment by YifanShenSZ** [comment]
I encountered this issue when trying to convert dynamic shape stories 110M to Core ML. These symbols & assertions seem shape range guard to me

**Comment by angelayi** [comment]
> torch.ops.aten._assert_scalar.default is scattered all over the program, which is not supported in Core ML so may lead to undesirable graph breaks

I don't have a lot of context on this, but it seems like another solution could be to consume the asserts to prevent the undesirable graph breaks, and then within your `preprocess` call, call [RemoveGraphAssertsPass](https://github.com/pytorch/executorch/blob/342e7f788210d8d6fe275eca2baf5c62238e337b/exir/passes/remove_graph_asserts_pass.py#L14) to remove these asserts, which will also call DCE and remove the unnecessary add/le/ge computations.

**Comment by YifanShenSZ** [comment]
> consume the asserts to prevent the undesirable graph breaks, and then within your preprocess call, call [RemoveGraphAssertsPass](https://github.com/pytorch/executorch/blob/342e7f788210d8d6fe275eca2baf5c62238e337b/exir/passes/remove_graph_asserts_pass.py#L14) to remove these asserts

Would it be dangerous to have delegate silently behave differently from the original program?

**Comment by angelayi** [comment]
> Would it be dangerous to have delegate silently behave differently from the original program?

These are just asserts so... I think it doesn't matter if you remove it? It's just a correctness check. 
ExecuTorch calls the same pass to remove asserts right before lowering to ExecuTorch runtime.

**Comment by cccclai** [comment]
It's probably better to have coreml consume these assert ops. 

For llama specifically, are those check [from the separate branch that are only for batch prefill](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/llama_transformer.py#L485-L500)? If yes, can we just don't use `.item` and unify the branches @angelayi @kimishpatel

**Comment by angelayi** [comment]
There's also a .item call [here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/llama_transformer.py#L168-L185), but I'm not sure how you would prevent using the .item call if you want a dynamic input position.

**Comment by cccclai** [comment]
@angelayi yeah I meant removing those `.item` call (like removing the if statement `if self.enable_dynamic_shape`), and just use else statement [these lines](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/llama_transformer.py#L187-L192). @kimishpatel  added the lines in `if self.enable_dynamic_shape` because he ran into export error when trying to export with dynamic shape, but I think we can export with dynamic shape directly with the original code directly

**Comment by YifanShenSZ** [comment]
>> consume the asserts to prevent the undesirable graph breaks, and then within your preprocess call, call [RemoveGraphAssertsPass](https://github.com/pytorch/executorch/blob/342e7f788210d8d6fe275eca2baf5c62238e337b/exir/passes/remove_graph_asserts_pass.py#L14) to remove these asserts

> It's probably better to have coreml consume these assert ops.

I see, I'll consume them in coreml and make them noops

**Comment by YifanShenSZ** [comment]
Consume all assertions and make them noops can successfully delegate the entire program to coreml 👏

However, the delegated edge program manager cannot be created. Probably due to torch.export requires some dynamic shape guard
```
Running MIL default pipeline: 100%|████████████████████████████████████████| 86/86 [00:18<00:00,  4.76 passes/s]
Running MIL backend_mlprogram pipeline: 100%|██████████████████████████████| 12/12 [00:00<00:00, 57.85 passes/s]
W0829 12:33:30.318000 58958 torch/fx/experimental/symbolic_shapes.py:5131] failed during evaluate_expr(s0 + u169 > 128, hint=None, expect_rational=True, size_oblivious=True, forcing_spec=False
E0829 12:33:30.318000 58958 torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(s0 + u169 > 128, None), **{'fx_node': False, 'size_oblivious': True})
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] failed while attempting to run meta for aten.slice_copy.Tensor
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] Traceback (most recent call last):
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 2023, in _dispatch_impl
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     r = func(*args, **kwargs)
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/_ops.py", line 713, in __call__
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     return self._op(*args, **kwargs)
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 781, in slice_forward
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     elif statically_known_true(end_val == sys.maxsize) or guard_size_oblivious(
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 253, in guard_size_oblivious
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     return expr.node.guard_size_oblivious("", 0)
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 503, in guard_size_oblivious
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     r = self.shape_env.evaluate_expr(
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     return retlog(fn(*args, **kwargs))
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5129, in evaluate_expr
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     return self._evaluate_expr(orig_expr, hint, fx_node, expect_rational, size_oblivious, forcing_spec=forcing_spec)
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5247, in _evaluate_expr
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     raise self._make_data_dependent_error(
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression u169 + 3 > 128 (unhinted: s0 + u169 > 128).  (Size-like symbols: none)
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] 
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] Potential framework code culprit (scroll up for full backtrace):
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]   File "/Volumes/Models/LLM/Framework/CoreMLTools-Dev_ExecuTorch-Dev_2024-08-28/envs/llama-py310/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 781, in slice_forward
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027]     elif statically_known_true(end_val == sys.maxsize) or guard_size_oblivious(
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] 
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] For more information, run with TORCH_LOGS="dynamic"
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u169"
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] 
E0829 12:33:30.321000 58958 torch/_subclasses/fake_tensor.py:2027] For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
```

**Comment by angelayi** [comment]
Do you happen to have a better stack trace of where this is being called? It's definitely because the asserts are being removed. After removing the asserts, you cannot run the model with fake tensors anymore, which happens when you re-export or run decompositions. If this is within the delegate, you can make a copy of the program so that removing the asserts do not affect the model when running eagerly.

**Comment by YifanShenSZ** [comment]
Sure, attached [stack-trace.txt](https://github.com/user-attachments/files/16820571/stack-trace.txt), which contains everything after conversion to Core ML

**Comment by kimishpatel** [comment]
@YifanShenSZ are you still blocked on this? @angelayi I see you made a suggestion on making a copy but not clear from Yifan's response if that workaround worked

**Comment by YifanShenSZ** [comment]
Yeah I couldn't workaround that 😞 still waiting for the checks to be removed, so on PyTorch conference we declared CoreML dynamic shape as "coming next"

**Comment by kimishpatel** [comment]
> the edge manager that replaces the delegated graph with

Yifan, so when you say you consumed/removed asserts inside coreml delegate, did you remove them from the copy of the exported program you receive, or no copy is made and input exported program is modified?

@cccclai we are hitting this in to_executorch and @angelayi suggests that this is due to asserts being removed. SO not clear if the 'exported program' being held inside delegate module is the one without asserts

**Comment by YifanShenSZ** [comment]
> Yifan, so when you say you consumed/removed asserts inside coreml delegate

I didn't modify the ExportedProgram. In fact, I don't think [coreml preprocessor](https://github.com/pytorch/executorch/blob/main/backends/apple/coreml/compiler/coreml_preprocess.py#L406-L437) ever modifies ExportedProgram?
```
class CoreMLBackend(BackendDetails):
    ...

    def preprocess(
        edge_program: ExportedProgram,
        compile_specs: List[CompileSpec],
    ) -> PreprocessResult:
        ...

        mlmodel = coremltools.convert(edge_program, ...)
        return CoreMLBackend.preprocess_model(mlmodel, model_type=model_type)
```
My consumption is in [coremltools](https://github.com/apple/coremltools/blob/main/coremltools/converters/mil/frontend/torch/ops.py#L5481-L5507), where I consider asserts as noops during torch op lowering
