### ISSUE TITLE
error while running the run.sh file

### ISSUE THREAD

**Issue by DeeN98** [pytorch/executorch#4771]
i have the file run.sh path_to_scratch_folder

Running e2e flow for model 'add' with flags '--delegate'
/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:106: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_byte.out")
/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:153: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_byte.dtype_out")
/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:228: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_4bit.out")
/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/passes/_quant_patterns_and_replacements.py:281: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @impl_abstract("quantized_decomposed::embedding_4bit.dtype_out")
W0817 04:07:48.057460 130982196246336 torch/_export/__init__.py:95] +============================+
W0817 04:07:48.057560 130982196246336 torch/_export/__init__.py:96] |     !!!   WARNING   !!!    |
W0817 04:07:48.057624 130982196246336 torch/_export/__init__.py:97] +============================+
W0817 04:07:48.057680 130982196246336 torch/_export/__init__.py:98] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
W0817 04:07:48.057737 130982196246336 torch/_export/__init__.py:99] Please switch to use torch.export instead.
Traceback (most recent call last):
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/backends/arm/arm_vela.py", line 47, in vela_compile
    subprocess.run([vela_command], shell=True, check=True, capture_output=True)
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cd /tmp/tmp6_324q02; vela --accelerator-config=ethos-u55-128 --config=Arm/vela.ini out.tosa']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/deepika/Downloads/executorch/executorch/examples/arm/aot_arm_compiler.py", line 213, in <module>
    edge = edge.to_backend(
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1166, in to_backend
    new_edge_programs[name] = to_backend(program, partitioner)
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 384, in _
    tagged_graph_module = _partition_and_lower(
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 299, in _partition_and_lower
    partitioned_module = _partition_and_lower_one_graph_module(
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 230, in _partition_and_lower_one_graph_module
    lowered_submodule = to_backend(
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 114, in _
    preprocess_result: PreprocessResult = cls.preprocess(
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/backends/arm/arm_backend.py", line 333, in preprocess
    binary = vela_compile(tosa_graph, compile_flags)
  File "/home/deepika/anaconda3/envs/executorch_new/lib/python3.10/site-packages/executorch/backends/arm/arm_vela.py", line 49, in vela_compile
    raise RuntimeError(
RuntimeError: Vela compiler ('cd /tmp/tmp6_324q02; vela --accelerator-config=ethos-u55-128 --config=Arm/vela.ini out.tosa') failed with error:
                                      Traceback (most recent call last):
  File "/home/deepika/anaconda3/envs/executorch_new/bin/vela", line 8, in <module>
    sys.exit(main())
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/vela.py", line 603, in main
    nng = process(
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/vela.py", line 80, in process
    compiler_driver.compiler_driver(nng, arch, compiler_options, scheduler_options, network_type, output_basename)
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/compiler_driver.py", line 192, in compiler_driver
    scheduler.schedule_passes(nng, arch, options, scheduler_options)
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/scheduler.py", line 1643, in schedule_passes
    opt_max_schedule = scheduler.propose_schedule_buffering(max_schedule_template, 1 << 32)
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/scheduler.py", line 644, in propose_schedule_buffering
    self.propose_operator_buffering(sched_op, prev_op, buffered_schedule, ref_schedule, staging_limit_bytes)
  File "/home/deepika/.local/lib/python3.10/site-packages/ethosu/vela/scheduler.py", line 667, in propose_operator_buffering
    cost.slack_buffering_memory = staging_limit_bytes - ref_memory_usage
OverflowError: Python integer 4294967296 out of bounds for int32

                                       Stdout:
Warning: Using internal-default values for system configuration
Warning: Using internal-default values for memory mode

**Comment by digantdesai** [comment]
cc @robell can you help with the vela error here?

**Comment by DeeN98** [comment]
Hello,
I have solved the error i think, as i extended the git post buffer it worked . 
I am not so sure but it worked for me.
