### ISSUE TITLE
QNN dl3: Unable to download dataset. Connection timed out 

### ISSUE THREAD

**Issue by guangy10** [pytorch/executorch#4950]
### 🐛 Describe the bug

Seems to be some instability issue. See the stacktrace:
```
  Traceback (most recent call last):
    File "/pytorch/executorch/examples/qualcomm/scripts/deeplab_v3.py", line 196, in <module>
      main(args)
    File "/pytorch/executorch/examples/qualcomm/scripts/deeplab_v3.py", line 77, in main
      inputs, targets, input_list = get_dataset(
    File "/pytorch/executorch/examples/qualcomm/scripts/deeplab_v3.py", line 41, in get_dataset
      datasets.VOCSegmentation(
    File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision/datasets/voc.py", line 98, in __init__
      download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.md5)
    File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 395, in download_and_extract_archive
      download_url(url, download_root, filename, md5)
    File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 122, in download_url
      url = _get_redirect_url(url, max_hops=max_redirect_hops)
    File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 66, in _get_redirect_url
      with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 519, in open
      response = self._open(req, data)
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 536, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
      result = func(*args)
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1377, in http_open
      return self.do_open(http.client.HTTPConnection, req)
    File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/py_3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/opt/conda/envs/py_3.10/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/pytorch/executorch/examples/qualcomm/scripts/deeplab_v3.py", line 202, in <module>
      raise Exception(e)
  Exception: <urlopen error [Errno 110] Connection timed out>
  ```

### Versions

Run on the latest main on the CI directly: https://github.com/pytorch/executorch/actions/runs/10602357194/job/29388115094

cc @cccclai @winskuo-quic @shewu-quic

**Comment by guangy10** [comment]
cc: @haowhsu-quic

**Comment by guangy10** [comment]
Decouple dataset downloading from model exporting in https://github.com/pytorch/executorch/pull/4961

**Comment by shewu-quic** [comment]
Hi @guangy10,
 just would like to follow up on this, are you still blocked on the issue?
