### ISSUE TITLE
./install_requirements.sh failed at news

### ISSUE THREAD

**Issue by JLake310** [pytorch/executorch#5064]
### 🐛 Describe the bug

Hi there,
I got an issue when installing newest version of ExecuTorch.

## Reproduce
```bash
git clone https://github.com/pytorch/executorch.git
cd executorch
git submodule sync
git submodule update --init
./install_requirements.sh
```

## Full Log
```bash
$ ./install_requirements.sh
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Requirement already satisfied: torch==2.5.0.dev20240901 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (2.5.0.dev20240901)
Requirement already satisfied: torchvision==0.20.0.dev20240901 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (0.20.0.dev20240901)
Requirement already satisfied: typing-extensions in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (4.12.2)
Requirement already satisfied: cmake in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (3.30.2)
Requirement already satisfied: pip>=23 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (24.2)
Requirement already satisfied: pyyaml in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (6.0.2)
Requirement already satisfied: setuptools>=63 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (72.1.0)
Requirement already satisfied: tomli in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: wheel in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (0.43.0)
Requirement already satisfied: zstd in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (1.5.5.1)
Requirement already satisfied: timm==1.0.7 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (1.0.7)
Requirement already satisfied: torchaudio==2.5.0.dev20240901 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (2.5.0.dev20240901)
Requirement already satisfied: torchsr==1.0.4 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (1.0.4)
Requirement already satisfied: transformers==4.42.4 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (4.42.4)
Requirement already satisfied: filelock in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torch==2.5.0.dev20240901) (3.15.4)
Requirement already satisfied: networkx in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torch==2.5.0.dev20240901) (3.3)
Requirement already satisfied: jinja2 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torch==2.5.0.dev20240901) (3.1.4)
Requirement already satisfied: fsspec in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torch==2.5.0.dev20240901) (2024.6.1)
Requirement already satisfied: sympy==1.13.1 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torch==2.5.0.dev20240901) (1.13.1)
Requirement already satisfied: numpy in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torchvision==0.20.0.dev20240901) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from torchvision==0.20.0.dev20240901) (10.4.0)
Requirement already satisfied: huggingface_hub in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from timm==1.0.7) (0.24.6)
Requirement already satisfied: safetensors in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from timm==1.0.7) (0.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from transformers==4.42.4) (24.1)
Requirement already satisfied: regex!=2019.12.17 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from transformers==4.42.4) (2024.7.24)
Requirement already satisfied: requests in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from transformers==4.42.4) (2.32.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from transformers==4.42.4) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from transformers==4.42.4) (4.66.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from sympy==1.13.1->torch==2.5.0.dev20240901) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from jinja2->torch==2.5.0.dev20240901) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from requests->transformers==4.42.4) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from requests->transformers==4.42.4) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from requests->transformers==4.42.4) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from requests->transformers==4.42.4) (2024.8.30)
Using pip 24.2 from /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/pip (python 3.10)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Processing /Users/jaeyeonkim/Desktop/newest/executorch
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info
  writing /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/dependency_links.txt
  writing entry points to /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/entry_points.txt
  writing requirements to /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/requires.txt
  writing top-level names to /private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/top_level.txt
  writing manifest file '/private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/SOURCES.txt'
  reading manifest file '/private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch.egg-info/SOURCES.txt'
  creating '/private/var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/pip-modern-metadata-hlk3028h/executorch-0.4.0a0+aca758d.dist-info'
  Preparing metadata (pyproject.toml) ... done
Collecting expecttest (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for expecttest from https://files.pythonhosted.org/packages/73/a8/9427813686fe043eaf817b99444d4d321ce14f9434e3ffb6bbd1a182a8df/expecttest-0.2.1-py3-none-any.whl.metadata
  Using cached expecttest-0.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting flatbuffers (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for flatbuffers from https://files.pythonhosted.org/packages/41/f0/7e988a019bc54b2dbd0ad4182ef2d53488bb02e58694cd79d61369e85900/flatbuffers-24.3.25-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Collecting hypothesis (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for hypothesis from https://files.pythonhosted.org/packages/e1/8c/8c58a2773d00bdfe6895180006127128c5dce51fafba984c530200e6fff6/hypothesis-6.111.2-py3-none-any.whl.metadata
  Using cached hypothesis-6.111.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: mpmath==1.3.0 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from executorch==0.4.0a0+aca758d) (1.3.0)
Requirement already satisfied: packaging in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from executorch==0.4.0a0+aca758d) (24.1)
Collecting parameterized (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for parameterized from https://files.pythonhosted.org/packages/00/2f/804f58f0b856ab3bf21617cccf5b39206e6c4c94c2cd227bde125ea6105f/parameterized-0.9.0-py2.py3-none-any.whl.metadata
  Using cached parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting pytest (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for pytest from https://files.pythonhosted.org/packages/0f/f9/cf155cf32ca7d6fa3601bc4c5dd19086af4b320b706919d48a4c79081cf9/pytest-8.3.2-py3-none-any.whl.metadata
  Using cached pytest-8.3.2-py3-none-any.whl.metadata (7.5 kB)
Collecting pytest-xdist (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for pytest-xdist from https://files.pythonhosted.org/packages/6d/82/1d96bf03ee4c0fdc3c0cbe61470070e659ca78dc0086fb88b66c185e2449/pytest_xdist-3.6.1-py3-none-any.whl.metadata
  Using cached pytest_xdist-3.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pyyaml in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from executorch==0.4.0a0+aca758d) (6.0.2)
Collecting ruamel.yaml (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for ruamel.yaml from https://files.pythonhosted.org/packages/73/67/8ece580cc363331d9a53055130f86b096bf16e38156e33b1d3014fffda6b/ruamel.yaml-0.18.6-py3-none-any.whl.metadata
  Using cached ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: sympy in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from executorch==0.4.0a0+aca758d) (1.13.1)
Collecting tabulate (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for tabulate from https://files.pythonhosted.org/packages/40/44/4a5f08c96eb108af5cb50b41f76142f0afa346dfa99d5296fe7202a11854/tabulate-0.9.0-py3-none-any.whl.metadata
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: typing-extensions in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from executorch==0.4.0a0+aca758d) (4.12.2)
Collecting numpy==1.21.3 (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for numpy==1.21.3 from https://files.pythonhosted.org/packages/0d/88/d65dd8c0c4e779c027928bc0be399beed44b2af256a895d7b3afb99b7f49/numpy-1.21.3-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.21.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting pandas==2.0.3 (from executorch==0.4.0a0+aca758d)
  Obtaining dependency information for pandas==2.0.3 from https://files.pythonhosted.org/packages/4a/f6/f620ca62365d83e663a255a41b08d2fc2eaf304e0b8b21bb6d62a7390fe3/pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.0.3->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for python-dateutil>=2.8.2 from https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.0.3->executorch==0.4.0a0+aca758d)
  Using cached https://download.pytorch.org/whl/nightly/pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting tzdata>=2022.1 (from pandas==2.0.3->executorch==0.4.0a0+aca758d)
  Using cached https://download.pytorch.org/whl/nightly/tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Collecting attrs>=22.2.0 (from hypothesis->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for attrs>=22.2.0 from https://files.pythonhosted.org/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl.metadata
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting sortedcontainers<3.0.0,>=2.1.0 (from hypothesis->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for sortedcontainers<3.0.0,>=2.1.0 from https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting exceptiongroup>=1.0.0 (from hypothesis->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for exceptiongroup>=1.0.0 from https://files.pythonhosted.org/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl.metadata
  Using cached exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting iniconfig (from pytest->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for iniconfig from https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl.metadata
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting pluggy<2,>=1.5 (from pytest->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for pluggy<2,>=1.5 from https://files.pythonhosted.org/packages/88/5f/e351af9a41f866ac3f1fac4ca0613908d9a41741cfcf2228f4ad853b697d/pluggy-1.5.0-py3-none-any.whl.metadata
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: tomli>=1 in /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages (from pytest->executorch==0.4.0a0+aca758d) (2.0.1)
Collecting execnet>=2.1 (from pytest-xdist->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for execnet>=2.1 from https://files.pythonhosted.org/packages/43/09/2aea36ff60d16dd8879bdb2f5b3ee0ba8d08cbbdcdfe870e695ce3784385/execnet-2.1.1-py3-none-any.whl.metadata
  Using cached execnet-2.1.1-py3-none-any.whl.metadata (2.9 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml->executorch==0.4.0a0+aca758d)
  Obtaining dependency information for ruamel.yaml.clib>=0.2.7 from https://files.pythonhosted.org/packages/61/ee/4874c9fc96010fce85abefdcbe770650c5324288e988d7a48b527a423815/ruamel.yaml.clib-0.2.8-cp310-cp310-macosx_13_0_arm64.whl.metadata
  Using cached ruamel.yaml.clib-0.2.8-cp310-cp310-macosx_13_0_arm64.whl.metadata (2.2 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.0.3->executorch==0.4.0a0+aca758d)
  Using cached https://download.pytorch.org/whl/nightly/six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached numpy-1.21.3-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
Using cached pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
Using cached expecttest-0.2.1-py3-none-any.whl (7.4 kB)
Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Using cached hypothesis-6.111.2-py3-none-any.whl (467 kB)
Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Using cached pytest-8.3.2-py3-none-any.whl (341 kB)
Using cached pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
Using cached ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Using cached execnet-2.1.1-py3-none-any.whl (40 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached ruamel.yaml.clib-0.2.8-cp310-cp310-macosx_13_0_arm64.whl (133 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Building wheels for collected packages: executorch
  Running command Building wheel for executorch (pyproject.toml)
  running bdist_wheel
  running build
  command options for 'CustomBuild':
    build_base = pip-out
    build_purelib = pip-out/lib
    build_platlib = pip-out/lib.macosx-11.1-arm64-cpython-310
    build_lib = pip-out/lib.macosx-11.1-arm64-cpython-310
    build_scripts = pip-out/scripts-3.10
    build_temp = pip-out/temp.macosx-11.1-arm64-cpython-310
    plat_name = macosx-11.1-arm64
    compiler = None
    parallel = 7
    debug = None
    force = None
    executable = /Users/jaeyeonkim/miniconda3/envs/executorch/bin/python
  creating /Users/jaeyeonkim/Desktop/newest/executorch/pip-out
  creating /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310
  creating /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out
  deleting /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/CMakeCache.txt
  cmake -S /Users/jaeyeonkim/Desktop/newest/executorch -B /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out -DBUCK2= -DPYTHON_EXECUTABLE=/Users/jaeyeonkim/miniconda3/envs/executorch/bin/python -DCMAKE_PREFIX_PATH=/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages -DCMAKE_BUILD_TYPE=Release -DEXECUTORCH_ENABLE_LOGGING=ON -DEXECUTORCH_LOG_LEVEL=Info -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DEXECUTORCH_SEPARATE_FLATCC_HOST_PROJECT=OFF -DEXECUTORCH_BUILD_KERNELS_CUSTOM=ON -DEXECUTORCH_BUILD_KERNELS_CUSTOM_AOT=ON -DEXECUTORCH_BUILD_KERNELS_QUANTIZED=ON -DEXECUTORCH_BUILD_KERNELS_QUANTIZED_AOT=ON
  -- The C compiler identification is AppleClang 15.0.0.15000309
  -- The CXX compiler identification is AppleClang 15.0.0.15000309
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading FXdiv to /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/FXdiv-source (define FXDIV_SOURCE_DIR to avoid it)
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/FXdiv-download
  [ 11%] Creating directories for 'fxdiv'
  [ 22%] Performing download step (git clone) for 'fxdiv'
  Cloning into 'FXdiv-source'...
  Already on 'master'
  Your branch is up to date with 'origin/master'.
  [ 33%] Performing update step for 'fxdiv'
  -- Fetching latest from the remote origin
  [ 44%] No patch step for 'fxdiv'
  [ 55%] No configure step for 'fxdiv'
  [ 66%] No build step for 'fxdiv'
  [ 77%] No install step for 'fxdiv'
  [ 88%] No test step for 'fxdiv'
  [100%] Completed 'fxdiv'
  [100%] Built target fxdiv
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Using python executable '/Users/jaeyeonkim/miniconda3/envs/executorch/bin/python'
  -- Resolved buck2 as /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/buck2-bin/buck2-99773fe6f7963a72ae5f7b737c02836e.
  -- Killing buck2 daemon
  -- executorch: Generating source lists
  -- executorch: Generating source file list /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/executorch_srcs.cmake
  Error while generating /Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/Users/jaeyeonkim/Desktop/newest/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/Users/jaeyeonkim/Desktop/newest/executorch/pip-out/temp.macosx-11.1-arm64-cpython-310/cmake-out/buck2-bin/buck2-99773fe6f7963a72ae5f7b737c02836e', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/Users/jaeyeonkim/Desktop/newest/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/Users/jaeyeonkim/Desktop/newest/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/Users/jaeyeonkim/Desktop/newest/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/Users/jaeyeonkim/Desktop/newest/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      0: Failed to stat `/Users/jaeyeonkim/Desktop/newest/executorch/buck-out/v2`
      1: ENOENT: No such file or directory


  CMake Error at build/Utils.cmake:204 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:337 (extract_sources)


  -- Configuring incomplete, errors occurred!
  error: command '/Users/jaeyeonkim/miniconda3/envs/executorch/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error

  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/jaeyeonkim/miniconda3/envs/executorch/bin/python /Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /var/folders/84/qbsh72hs3h110p5hjh_g5mvh0000gn/T/tmp6hdnmmkx
  cwd: /Users/jaeyeonkim/Desktop/newest/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (executorch)
Traceback (most recent call last):
  File "/Users/jaeyeonkim/Desktop/newest/executorch/./install_requirements.py", line 160, in <module>
    subprocess.run(
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jaeyeonkim/miniconda3/envs/executorch/bin/python', '-m', 'pip', 'install', '.', '--no-build-isolation', '-v', '--extra-index-url', 'https://download.pytorch.org/whl/nightly/cpu']' returned non-zero exit status 1.
```

### Versions

PyTorch version: 2.5.0.dev20240901
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.2
Libc version: N/A

Python version: 3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240901
[pip3] torchaudio==2.5.0.dev20240901
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240901
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.5.0.dev20240901          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20240901          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240901          pypi_0    pypi

**Comment by dvorjackz** [comment]
Can you try `rm -rf buck-out`?

**Comment by JLake310** [comment]
@dvorjackz I already did but still the error occurs.

**Comment by grisaitis** [comment]
Same happened to me. Rebooting fixed it. Logging out and back in (on macOS) did not. 

perhaps related are these issues mentioning "Buck appears to be running in a stale working directory":
- https://github.com/pytorch/executorch/issues/3802
- https://github.com/pytorch/executorch/issues/4439
- https://github.com/pytorch/executorch/issues/4480
