### ISSUE TITLE
./install_requirements.sh fails when building from a repo directory whose name is not `executorch`

### ISSUE THREAD

**Issue by dvorjackz** [pytorch/executorch#5610]
### 🐛 Describe the bug

When running:

```
rm -rf cmake-out pip-out buck-out

./install_requirements.sh
```

I get the following on tip of main (`3e79ea4135824662cbeef6e84c1ce3a989f03ad3`):

```
[ 66%] Building C object kernels/optimized/CMakeFiles/eigen_blas.dir/third-party/eigen/blas/f2c/complexdots.c.o
  [ 66%] Building CXX object CMakeFiles/executorch_no_prim_ops.dir/runtime/core/evalue.cpp.o
  [ 66%] Building CXX object CMakeFiles/executorch_no_prim_ops.dir/runtime/backend/interface.cpp.o
  [ 69%] Building CXX object CMakeFiles/executorch_no_prim_ops.dir/runtime/core/exec_aten/util/tensor_util_portable.cpp.o
  /home/jackzhxng/executorch_wt1/runtime/core/evalue.cpp:9:10: fatal error: executorch/runtime/core/evalue.h: No such file or directory
      9 | #include <executorch/runtime/core/evalue.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/jackzhxng/executorch_wt1/runtime/core/exec_aten/util/tensor_util_portable.cpp:9:10: fatal error: executorch/runtime/core/exec_aten/util/tensor_util.h: No such file or directory
      9 | #include <executorch/runtime/core/exec_aten/util/tensor_util.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  compilation terminated.
  /home/jackzhxng/executorch_wt1/runtime/backend/interface.cpp:9:10: fatal error: executorch/runtime/backend/interface.h: No such file or directory
      9 | #include <executorch/runtime/backend/interface.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  gmake[3]: *** [CMakeFiles/executorch_no_prim_ops.dir/build.make:104: CMakeFiles/executorch_no_prim_ops.dir/runtime/core/exec_aten/util/tensor_util_portable.cpp.o] Error 1
  gmake[3]: *** Waiting for unfinished jobs....
  gmake[3]: *** [CMakeFiles/executorch_no_prim_ops.dir/build.make:90: CMakeFiles/executorch_no_prim_ops.dir/runtime/core/evalue.cpp.o] Error 1
  gmake[3]: *** [CMakeFiles/executorch_no_prim_ops.dir/build.make:76: CMakeFiles/executorch_no_prim_ops.dir/runtime/backend/interface.cpp.o] Error 1
  [ 69%] Building CXX object CMakeFiles/executorch_no_prim_ops.dir/runtime/core/portable_type/tensor_impl.cpp.o
  [ 69%] Linking C static library libcpuinfo.a
  /home/jackzhxng/executorch_wt1/runtime/core/portable_type/tensor_impl.cpp:9:10: fatal error: executorch/runtime/core/portable_type/tensor_impl.h: No such file or directory
      9 | #include <executorch/runtime/core/portable_type/tensor_impl.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  gmake[3]: *** [CMakeFiles/executorch_no_prim_ops.dir/build.make:118: CMakeFiles/executorch_no_prim_ops.dir/runtime/core/portable_type/tensor_impl.cpp.o] Error 1
  gmake[2]: *** [CMakeFiles/Makefile2:337: CMakeFiles/executorch_no_prim_ops.dir/all] Error 2
  gmake[2]: *** Waiting for unfinished jobs....
  [ 69%] Built target cpuinfo
  [ 72%] Linking C static library libpthreadpool.a
  [ 72%] Built target pthreadpool
  [ 72%] Linking CXX static library libeigen_blas.a
  [ 72%] Built target eigen_blas
  gmake[1]: *** [CMakeFiles/Makefile2:929: extension/llm/custom_ops/CMakeFiles/custom_ops_aot_lib.dir/rule] Error 2
  gmake: *** [Makefile:429: custom_ops_aot_lib] Error 2
  error: command '/home/jackzhxng/.conda/envs/et-worktree/bin/cmake' failed with exit code 2
  error: subprocess-exited-with-error
  
  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/jackzhxng/.conda/envs/et-worktree/bin/python /home/jackzhxng/.conda/envs/et-worktree/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp8s9lzyr6
  cwd: /home/jackzhxng/executorch_wt1
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (executorch)
Traceback (most recent call last):
  File "/home/jackzhxng/executorch_wt1/./install_requirements.py", line 160, in <module>
    subprocess.run(
  File "/home/jackzhxng/.conda/envs/et-worktree/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jackzhxng/.conda/envs/et-worktree/bin/python', '-m', 'pip', 'install', '.', '--no-build-isolation', '-v', '--extra-index-url', 'https://download.pytorch.org/whl/nightly/cpu']' returned non-zero exit status 1.
```

### Versions

```
PyTorch version: 2.5.0.dev20240901+cpu                                                                                                                         
Is debug build: False                                                    
CUDA used to build PyTorch: Could not collect                                                                                                                  
ROCM used to build PyTorch: N/A     

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2)
Clang version: Could not collect
CMake version: version 3.30.3
Libc version: glibc-2.34

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-6.4.3-0_fbk12_hardened_2624_g7d95a0297d81-x86_64-with-glibc2.34
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA PG509-210
Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             22
On-line CPU(s) list:                0-21
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                         6
Model:                              85
Thread(s) per core:                 1
Core(s) per socket:                 22
Socket(s):                          1
Stepping:                           11
BogoMIPS:                           3591.61
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 arat vnmi umip pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                     VT-x
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          704 KiB (22 instances)
L1i cache:                          704 KiB (22 instances)
L2 cache:                           88 MiB (22 instances)
L3 cache:                           16 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-21
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Vulnerable
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240901+cpu
[pip3] torchao==0.5.0+git0916b5b
[pip3] torchaudio==2.5.0.dev20240901+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240901+cpu
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.5.0.dev20240901+cpu          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20240901+cpu          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240901+cpu          pypi_0    pypi
```

**Comment by dvorjackz** [comment]
Makes sense, I was on a et git worktree
