### ISSUE TITLE
Pte export of llama model

### ISSUE THREAD

**Issue by Vinaysukhesh98** [pytorch/executorch#5751]
### 🐛 Describe the bug

python -m examples.models.llama2.export_llama --checkpoint "${MODEL_DIR}/model.pth" -p "${MODEL_DIR}/original/params.json" -kv --disable_dynamic_shape --qnn --pt2e_quantize qnn_16a4w -d fp32 --metadata '{"get_bos_id":128000, "get_eos_ids":[128009, 128001]}' --soc_model SM8650 --output_name="test.pte"

nomodule error ModuleNotFoundError: No module named 'executorch.backends.qualcomm.python'

### Versions

python -m examples.models.llama2.export_llama --checkpoint "${MODEL_DIR}/model.pth" -p "${MODEL_DIR}/original/params.json" -kv --disable_dynamic_shape --qnn --pt2e_quantize qnn_16a4w -d fp32 --metadata '{"get_bos_id":128000, "get_eos_ids":[128009, 128001]}' --soc_model SM8650 --output_name="test.pte"
 /Documents/vinay/executorch/examples/models/llama2/model.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=device, mmap=True)
Traceback (most recent call last):
  File " /anaconda3/envs/et_qnn/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File " /anaconda3/envs/et_qnn/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama_lib.py", line 449, in export_llama
    builder = _export_llama(modelname, args)
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama_lib.py", line 549, in _export_llama
    _prepare_for_llama_export(modelname, args)
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama_lib.py", line 505, in _prepare_for_llama_export
    .source_transform(_get_source_transforms(modelname, dtype_override, args))
  File " /Documents/vinay/executorch/examples/models/llama2/export_llama_lib.py", line 886, in _get_source_transforms
    from executorch.backends.qualcomm.utils.utils import (
  File " /anaconda3/envs/et_qnn/lib/python3.10/site-packages/executorch/backends/qualcomm/utils/utils.py", line 12, in <module>
    import executorch.backends.qualcomm.python.PyQnnManagerAdaptor as PyQnnManagerAdaptor
ModuleNotFoundError: No module named 'executorch.backends.qualcomm.python'

cc @cccclai @winskuo-quic @shewu-quic

**Comment by iseeyuan** [comment]
@cccclai , could you help look at this?

**Comment by cccclai** [comment]
Did you run these two commands? 
```
cp -f backends/qualcomm/PyQnnManagerAdaptor.cpython-310-x86_64-linux-gnu.so $EXECUTORCH_ROOT/backends/qualcomm/python
cp -f backends/qualcomm/PyQnnWrapperAdaptor.cpython-310-x86_64-linux-gnu.so $EXECUTORCH_ROOT/backends/qualcomm/python
```
Full instruction here https://pytorch.org/executorch/main/build-run-qualcomm-ai-engine-direct-backend.html

**Comment by Vinaysukhesh98** [comment]
> Did you run these two commands?
> 
> ```
> cp -f backends/qualcomm/PyQnnManagerAdaptor.cpython-310-x86_64-linux-gnu.so $EXECUTORCH_ROOT/backends/qualcomm/python
> cp -f backends/qualcomm/PyQnnWrapperAdaptor.cpython-310-x86_64-linux-gnu.so $EXECUTORCH_ROOT/backends/qualcomm/python
> ```
> 
> Full instruction here https://pytorch.org/executorch/main/build-run-qualcomm-ai-engine-direct-backend.html

Could you help me with llama3.2 model export command in int 4quant format

**Comment by cbilgin** [comment]
@Vinaysukhesh98 Looks like the original problem is resolved. If you are still looking for support on running Llama3.2 on QNN, do you mind giving a try with the new release and opening up a new issue with any error you might be seeing?

**Comment by Vinaysukhesh98** [comment]
Rebuild process failing at below step:

./backends/qualcomm/scripts/build.sh --release

cmake -DPYTHON_EXECUTABLE=python \
    -DCMAKE_INSTALL_PREFIX=cmake-out \
    -DEXECUTORCH_ENABLE_LOGGING=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DEXECUTORCH_BUILD_EXTENSION_MODULE=ON \
    -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON \
    -DEXECUTORCH_BUILD_EXTENSION_TENSOR=ON \
    -DEXECUTORCH_BUILD_QNN=ON \
    -DQNN_SDK_ROOT=${QNN_SDK_ROOT} \
    -DEXECUTORCH_BUILD_KERNELS_QUANTIZED=ON \
    -DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
    -DEXECUTORCH_BUILD_KERNELS_CUSTOM=ON \
    -Bcmake-out .
cmake --build cmake-out -j16 --target install --config Release

Error: 
KERNEL_LIBS: portable_kernels
--   DEPS: executorch
CMake Error at build/Utils.cmake:340 (find_package):
  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:618 (find_package_torch_headers)


-- Configuring incomplete, errors occurred!
gmake: Makefile: No such file or directory

**Comment by Vinaysukhesh98** [comment]
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default
No quant config is implemented for op, aten.copy_.default

What does above message reffers to?

**Comment by Vinaysukhesh98** [comment]
![Image](https://github.com/user-attachments/assets/b90edc62-1612-43b2-9dc2-600879e3ece3)
this is how thw executorch o/p looks like
 ETLogging               com.example.executorchllamademo      D  Load complete. Model path: /data/local/tmp/llama/llama-3_2-3b-int4.pte
                                                                                                    Tokenizer path: /data/local/tmp/llama/tokenizer_Llama-3.2-3B-Chat.bin
                                                                                                    Backend: QUALCOMM
                                                                                                    ModelType: 1
                                                                                                    Temperature: 0.0
                                                                                                    Model loaded time: 3411 ms
2025-02-13 16:10:00.357 28525-677   utorchllamademo         com.example.executorchllamademo      W  Cleared Reference was only reachable from finalizer (only reported once)
2025-02-13 16:10:00.374 28525-677   utorchllamademo         com.example.executorchllamademo      I  This is non sticky GC, maxfree is 16777216 minfree is 8388608
2025-02-13 16:10:00.401 28525-28525 FinalizerDaemon         com.example.executorchllamademo      W  type=1400 audit(0.0:2854): avc:  denied  { getopt } for  path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app_32:s0:c70,c257,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=com.example.executorchllamademo
2025-02-13 16:10:00.405 28525-679   utorchllamademo         com.example.executorchllamademo      W  ApkAssets: Deleting an ApkAssets object '<empty> and /product/app/MiuiContentCatcherMIUI15/MiuiContentCatcherMIUI15.apk' with 1 weak references
2025-02-13 16:10:00.405 28525-679   utorchllamademo         com.example.executorchllamademo      W  ApkAssets: Deleting an ApkAssets object '<empty> and /system_ext/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk' with 1 weak references
2025-02-13 16:10:00.405 28525-679   utorchllamademo         com.example.executorchllamademo      W  ApkAssets: Deleting an ApkAssets object '<empty> and /system_ext/app/miuisystem/miuisystem.apk' with 1 weak references
2025-02-13 16:10:03.650 28525-28525 Editor                  com.example.executorchllamademo      D  Double tap detection is fail
2025-02-13 16:10:03.755 28525-28525 HandWritingStubImpl     com.example.executorchllamademo      I  refreshLastKeyboardType: 1
2025-02-13 16:10:03.759 28525-28525 HandWritingStubImpl     com.example.executorchllamademo      I  getCurrentKeyboardType: 1
2025-02-13 16:10:03.763 28525-28525 Compatibil...geReporter com.example.executorchllamademo      D  Compat change id reported: 163400105; UID 10326; state: ENABLED
2025-02-13 16:10:03.765 28525-28525 ImeTracker              com.example.executorchllamademo      I  com.example.executorchllamademo:5013c9eb: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
2025-02-13 16:10:03.765 28525-28525 InputMethodManager      com.example.executorchllamademo      D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{6818347 VFED..CL. .F.P..ID 132,0-1068,105 #7f0800bc app:id/editTextMessage aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
2025-02-13 16:10:03.775 28525-28525 TextViewImpl            com.example.executorchllamademo      V  sendCursorInfo support:true
2025-02-13 16:10:03.781 28525-28525 AssistStructure         com.example.executorchllamademo      I  Flattened final assist data: 1944 bytes, containing 1 windows, 11 views
2025-02-13 16:10:03.817 28525-28525 InsetsController        com.example.executorchllamademo      D  show(ime(), fromIme=true)
2025-02-13 16:10:04.043 28525-28525 ImeTracker              com.example.executorchllamademo      I  com.example.executorchllamademo:5013c9eb: onShown
2025-02-13 16:10:09.257 28525-28525 ImeTracker              com.example.executorchllamademo      I  com.example.executorchllamademo:d1724b2e: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
2025-02-13 16:10:09.265 28525-1504  ETLogging               com.example.executorchllamademo      D  starting runnable generate()
2025-02-13 16:10:09.265 28525-1504  ETLogging               com.example.executorchllamademo      D  Running inference.. prompt=<|begin_of_text|><|start_header_id|>system<|end_header_id|>
                                                                                                    <|eot_id|><|start_header_id|>user<|end_header_id|>
                                                                                                    what is llama<|eot_id|><|start_header_id|>assistant<|end_header_id|>
2025-02-13 16:10:09.265 28525-1504  ExecuTorch              com.example.executorchllamademo      I  RSS after loading model: 2573.082031 MiB (0 if unsupported)
2025-02-13 16:10:09.351 28525-28525 WindowOnBackDispatcher  com.example.executorchllamademo      W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@40449716 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@4e48c72
2025-02-13 16:10:09.596 28525-28525 ImeTracker              com.example.executorchllamademo      I  com.example.executorchllamademo:c7454d39: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2025-02-13 16:10:09.598 28525-28525 ImeTracker              com.example.executorchllamademo      I  com.example.executorchllamademo:d1724b2e: onHidden
2025-02-13 16:10:10.988 28525-1504  ExecuTorch              com.example.executorchllamademo      I  RSS after prompt prefill: 2573.082031 MiB (0 if unsupported)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  RSS after finishing text generation: 2573.082031 MiB (0 if unsupported)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  	Prompt Tokens: 17    Generated Tokens: 110
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  	Model Load Time:		0.000000 (seconds)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  	Total inference time:		12.407000 (seconds)		 Rate: 	8.865963 (tokens/second)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  		Prompt evaluation:	1.723000 (seconds)		 Rate: 	9.866512 (tokens/second)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  		Generated 110 tokens:	10.684000 (seconds)		 Rate: 	10.295769 (tokens/second)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  	Time to first generated token:	1.723000 (seconds)
2025-02-13 16:10:21.672 28525-1504  ExecuTorch              com.example.executorchllamademo      I  	Sampling time over 127 tokens:	0.029000 (seconds)
2025-02-13 16:10:21.673 28525-1504  ETLogging               com.example.executorchllamademo      D  Inference completed
