### ISSUE TITLE
export llama 3.2-1B error with executorch 4.0 and main

### ISSUE THREAD

**Issue by fighting300** [pytorch/executorch#7263]
### 🐛 Describe the bug

1. when i export llama 3.2-1B with executorch 4.0, there is a error blow;

python -m examples.models.llama2.export_llama  --checkpoint  /Users/tanwei/.llama/checkpoints/Llama3.2-1B-Instruct/consolidated.00.pth  --params   /Users/tanwei/.llama/checkpoints/Llama3.2-1B-Instruct/params.json  -kv --use_sdpa_with_kv_cache -X -qmode 8da4w --group_size 128 -d fp32
/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/model.py:101: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See 
https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models
 for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=device, mmap=True)
W1210 16:18:22.692745 49662 site-packages/torch/_export/__init__.py:64] +============================+
W1210 16:18:22.693156 49662 site-packages/torch/_export/__init__.py:65] |     !!!   WARNING   !!!    |
W1210 16:18:22.693295 49662 site-packages/torch/_export/__init__.py:66] +============================+
W1210 16:18:22.693485 49662 site-packages/torch/_export/__init__.py:67] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
W1210 16:18:22.693619 49662 site-packages/torch/_export/__init__.py:68] Please switch to use torch.export.export_for_training instead.

/Users/tanwei/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/emit/_emitter.py:1512: UserWarning: Mutation on a buffer in the model is detected. ExecuTorch assumes buffers that are mutated in the graph have a meaningless initial state, only the shape and dtype will be serialized.
  warnings.warn(

2. when i run export llama 3.2-1B-qlora ,there is error blow:  
 Traceback (most recent call last):
  File "/Users/tanwei/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tanwei/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama_lib.py", line 411, in export_llama
    builder = _export_llama(modelname, args)
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama_lib.py", line 510, in _export_llama
    _prepare_for_llama_export(modelname, args)
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama_lib.py", line 444, in _prepare_for_llama_export
    _load_llama_model(
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/export_llama_lib.py", line 694, in _load_llama_model
    model, example_inputs, _ = EagerModelFactory.create_model(
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/model_factory.py", line 44, in create_model
    model = model_class(**kwargs)
  File "/Users/tanwei/Desktop/Model/executorch/examples/models/llama2/model.py", line 146, in __init__
    model_args: ModelArgs = ModelArgs(
TypeError: ModelArgs.__init__() got an unexpected keyword argument 'quantization_args'

3. when i run export with branch main , there is a error blow :

No source file  tensor_impl_ptr.cpp when build wheel.

### Versions

Collecting environment information...
PyTorch version: 2.6.0.dev20241112
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: version 3.31.1
Libc version: N/A

Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M4 Pro

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+6a085ff
[pip3] numpy==1.26.4
[pip3] onnx==1.17.0
[pip3] onnx-weekly==1.18.0.dev20241203
[pip3] onnxruntime==1.20.1
[pip3] onnxscript==0.1.0.dev20241204
[pip3] torch==2.5.0
[pip3] torchao==0.5.0+git0916b5b2
[pip3] torchaudio==2.5.0
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0
[conda] executorch                0.4.0a0+6a085ff          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.6.0.dev20241112          pypi_0    pypi
[conda] torchao                   0.5.0+git0916b5b2          pypi_0    pypi
[conda] torchaudio                2.5.0                    pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20241112          pypi_0    pypi

**Comment by Jack-Khuu** [comment]
@lucylq Is this up your alley?

**Comment by BodhiHu** [comment]
we met the same issue:
```
 CMake Error at extension/tensor/CMakeLists.txt:20 (add_library):
    Cannot find source file:

      /home/mt/bodhi/executorch/extension/tensor/tensor_impl_ptr.cpp
```

**Comment by lucylq** [comment]
Hi @fighting300 and @BodhiHu, thanks for your patience. 

I think by default `EXTENSION_MODULE` isn't built in the root CMakeLists.txt, could you try setting it to ON here? https://github.com/pytorch/executorch/blob/main/CMakeLists.txt#L187

**Comment by nil-is-all** [comment]
Hi @fighting300, were you able to try setting 'EXTENSION_MODULE' to ON and re-running './install_requirements.sh'? Are you still facing any issues?
