### ISSUE TITLE
buck2 needs to be updated past https://github.com/facebook/buck2/pull/693 (June 28, 2024) so executorch can build on Raspberry Pi 5

### ISSUE THREAD

**Issue by swolchok** [pytorch/executorch#7425]
### 🐛 Describe the bug

Attempting to build ExecuTorch on Raspberry Pi 5 fails with:

```
-- executorch: Generating source lists
-- executorch: Generating source file list /home/swolchok/src/torchchat/et-build/src/executorch/cmake-out/executorch_srcs.cmake
Error while generating /home/swolchok/src/torchchat/et-build/src/executorch/cmake-out/executorch_srcs.cmake. Exit code: 1
Output:

Error:
Traceback (most recent call last):
  File "/home/swolchok/src/torchchat/et-build/src/executorch/build/buck_util.py", line 26, in run
    cp: subprocess.CompletedProcess = subprocess.run(
                                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/swolchok/src/torchchat/et-build/src/executorch/cmake-out/buck2-bin/buck2-49670bee56a7d8a7696409ca6fbf7551d2469787', 'cquery', "inputs(deps('//runtime/executor:program'))"]' died with <Signals.SIGABRT: 6>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/swolchok/src/torchchat/et-build/src/executorch/build/extract_sources.py", line 232, in <module>
    main()
  File "/home/swolchok/src/torchchat/et-build/src/executorch/build/extract_sources.py", line 217, in main
    target_to_srcs[name] = sorted(target.get_sources(graph, runner, buck_args))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swolchok/src/torchchat/et-build/src/executorch/build/extract_sources.py", line 121, in get_sources
    sources: set[str] = set(runner.run(["cquery", query] + buck_args))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swolchok/src/torchchat/et-build/src/executorch/build/buck_util.py", line 31, in run
    raise RuntimeError(ex.stderr.decode("utf-8")) from ex
RuntimeError: <jemalloc>: Unsupported system page size
memory allocation of 64 bytes failed


CMake Error at build/Utils.cmake:216 (message):
  executorch: source list generation failed
Call Stack (most recent call first):
  CMakeLists.txt:376 (extract_sources)
```

Raspberry Pi 5 ships with 16 KiB page size.

### Versions

Raspberry Pi 5.

**Comment by swolchok** [comment]
I have confirmed that https://github.com/facebook/buck2/releases/tag/2024-07-01 can run on Raspberry Pi 5 and the previous release (2024-06-15) cannot.
